[Debugger] Add support for quoted identifiers
ballerina-platform/ballerina-lang pull request #26018
Opened 2020-09-23 04:34 UTC by NipunaRanasinghe

## Purpose
This PR updates debugger variable implementation and the expression evaluation implementation to support recent changes introduced to quoted identifiers.

Fixes https://github.com/ballerina-platform/ballerina-lang/issues/25731

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2020-09-23 12:14 UTC, HindujaB approved these changes
This looks good to me.

2020-09-24 05:12 UTC, hevayo requested changes
@NipunaRanasinghe shall we add some test with quoted identifiers.

2020-09-24 05:15 UTC, NipunaRanasinghe commented
> @NipunaRanasinghe shall we add some test with quoted identifiers.

@hevayo I was planning to add tests in a separate PR, but can do in here too. +1

2020-09-25 05:24 UTC, praveennadarajah approved these changes

2020-09-25 06:45 UTC, hevayo approved these changes

2020-09-25 06:45 UTC, merged