Fix the concurrent behaviour issue of cache
ballerina-platform/ballerina-lang pull request #26385
Opened 2020-10-16 10:31 UTC by kalaiyarasiganeshalingam

## Purpose
$Subject

Fixes [#27](https://github.com/ballerina-platform/module-ballerina-cache/issues/27)

2020-10-17 01:30 UTC, ldclakmal requested changes
@kalaiyarasiganeshalingam You have implemented the `compare and swap` technique, but it is not used at `remove` method of the `LinkedList`. Still the `boolean` usage is there.

2020-10-17 07:36 UTC, kalaiyarasiganeshalingam commented
> @kalaiyarasiganeshalingam You have implemented the `compare and swap` technique, but it is not used at `remove` method of the `LinkedList`. Still the `boolean` usage is there.

When I added the LinkedList object impl, that changes have been overwritten. I have re-added that.

2020-10-17 13:48 UTC, ldclakmal commented on stdlib/cache/src/main/ballerina/src/cache/linked_list.bal
> +        // removed from the cache.
Shall we remove this, since this is no longer valid?

2020-10-17 13:48 UTC, ldclakmal commented on stdlib/cache/src/main/ballerina/src/cache/linked_list.bal
> +        //externSetLock();
```suggestion
```

2020-10-17 13:50 UTC, ldclakmal commented on stdlib/cache/src/main/java/org/ballerinalang/stdlib/cache/nativeimpl/Lock.java
> +    public static void setLock() {
```suggestion
    public static void releaseLock() {
```

2020-10-17 13:51 UTC, ldclakmal commented on stdlib/cache/src/main/ballerina/src/cache/linked_list.bal
> +} external;
```suggestion
function releaseLock() = @java:Method {
    class: "org.ballerinalang.stdlib.cache.nativeimpl.Lock"
} external;
```

2020-10-17 13:54 UTC, ldclakmal commented on stdlib/cache/src/main/java/org/ballerinalang/stdlib/cache/nativeimpl/Lock.java
> +    }
```suggestion
    public static boolean tryLock() {
        return locked.compareAndSet(false, true);
    }
```

2020-10-17 13:54 UTC, ldclakmal commented on stdlib/cache/src/main/java/org/ballerinalang/stdlib/cache/nativeimpl/Lock.java
> +    }
```suggestion
    public static void releaseLock() {
        locked.set(false);
    }
```

2020-10-17 13:55 UTC, ldclakmal commented on stdlib/cache/src/main/ballerina/src/cache/linked_list.bal
> +} external;
```suggestion
function tryLock() returns boolean = @java:Method {
    class: "org.ballerinalang.stdlib.cache.nativeimpl.Lock"
} external;
```

2020-10-17 13:55 UTC, ldclakmal commented on stdlib/cache/src/main/ballerina/src/cache/linked_list.bal
> +        if (externCheckState()) {
```suggestion
        if (tryLock()) {
```

2020-10-17 13:56 UTC, ldclakmal commented on stdlib/cache/src/main/ballerina/src/cache/linked_list.bal
> +        //externSetLock();
```suggestion
            node.prev = ();
            releaseLock();
        }
```

2020-10-17 13:58 UTC, ldclakmal commented on stdlib/cache/src/main/java/org/ballerinalang/stdlib/cache/nativeimpl/Lock.java
> + * Class to handle ballerina external functions in Cache library.
```suggestion
 * Class to handle concurrency behaviour of `LinkedList` using compare and swap technique.
```

2020-10-18 13:18 UTC, ldclakmal commented
@kalaiyarasiganeshalingam Shall we compare and see the performance numbers before the fix and after the fix using the below sample?
https://github.com/ldclakmal/ballerina-samples/blob/master/src/cache/cache-performance.bal

2020-10-19 05:01 UTC, kalaiyarasiganeshalingam commented
> @kalaiyarasiganeshalingam Shall we compare and see the performance numbers before the fix and after the fix using the below sample?
> https://github.com/ldclakmal/ballerina-samples/blob/master/src/cache/cache-performance.bal

The performance test output: https://docs.google.com/document/d/1gE6PtUEgqTBcgk_1ORDsIud4Ou9-B-T-5d34C9xkmcE/edit?usp=sharing

2020-10-19 05:08 UTC, ldclakmal approved these changes
LGTM

2020-10-19 06:14 UTC, daneshk approved these changes

2020-10-19 06:15 UTC, merged