Add support for Class symbols
ballerina-platform/ballerina-lang pull request #26703
Opened 2020-11-02 13:05 UTC by pubudu91

## Purpose
This PR adds a separate symbol for classes.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2020-11-04 03:04 UTC, nadeeshaan requested changes

2020-11-04 06:19 UTC, SupunS commented on tests/ballerina-compiler-api-test/src/test/resources/test-src/class_symbols_test.bal
> +}
Missing eof

2020-11-04 07:08 UTC, pubudu91 commented on compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
> +
Can't really do that right? What's being checked here is the following case:
```ballerina
type Person record {|
    string name;
|};

function bar() {
    <cursor>Person p = { name: "Pubudu" };
}
```
In this case, I want to return a `TypeReferenceTypeSymbol` instance, not a `TypeDefinitionSymbol`. To check which one to return, have to check the `BSymbol`'s position against the user provided position.

2020-11-04 10:58 UTC, SupunS commented on compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
> +
In the AST we would know its a type-reference right? 
for e.g.: in `public void visit(BLangSimpleVariable varNode) {}` method, we know what we need to return is a `TypeReferenceTypeSymbol`

2020-11-04 12:02 UTC, pubudu91 commented on compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/BallerinaSemanticModel.java
> +
Yeah, but the thing is, we return a `BSymbol` from the `SymbolFinder`, not the node.

2020-11-05 11:11 UTC, SupunS approved these changes

2020-11-05 11:12 UTC, nadeeshaan approved these changes

2020-11-05 11:13 UTC, merged