Fix transaction validating if rollback is used with if condition
ballerina-platform/ballerina-lang pull request #26968
Opened 2020-11-17 04:54 UTC by lasinicl

## Purpose
> $title and remove transactional resource function test from ballerina-lang
Fixes #26854

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2020-11-17 06:31 UTC, pcnfernando commented
Added a comment on a test corresponding to this change in https://github.com/ballerina-platform/module-ballerinai-transaction/pull/8/files

2020-11-18 14:07 UTC, lasinicl commented
> Added a comment on a test corresponding to this change in https://github.com/ballerina-platform/module-ballerinai-transaction/pull/8/files

Fixed in 5bfabb3

2020-11-19 05:49 UTC, pcnfernando requested changes

2020-11-19 05:49 UTC, pcnfernando commented on compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/CodeAnalyzer.java
> +    private boolean withinIfBlock;
Can't we have a constraint just in case we have an if-else and within them we have commit and rollback, the following will be non tractional

2020-12-04 05:49 UTC, closed without merging

2020-12-04 07:53 UTC, lasinicl commented
Accidentally closed due to a forced push.
Please find the new PR here https://github.com/ballerina-platform/ballerina-lang/pull/27339