Fix diagnostics duplication and perf issue
ballerina-platform/ballerina-lang pull request #27240
Opened 2020-11-29 02:24 UTC by rasika

## Purpose
> Fix diagnostics duplication and perf issue

Fixes #27238
Fixes #27239

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2020-11-30 04:01 UTC, nadeeshaan requested changes

2020-12-02 04:08 UTC, SupunS requested changes
The method `getNodeBasedCodeActions` is very long. Can we break it into smaller methods?

Also we do a manual to-string conversion of the diagnostics for recreating imports list. Can't we use syntax tree's `toSourceCode` method?

2020-12-02 06:48 UTC, rasika commented
@SupunS I broke the method into smaller parts having that change in local with a small packaging restructure. Will send in a separate PR. +1 for the `toSourceCode` will add it too.

2020-12-02 16:41 UTC, rasika commented
@nadeeshaan @SupunS Added suggested changes.

2020-12-02 17:26 UTC, nadeeshaan approved these changes

2020-12-03 02:42 UTC, SupunS approved these changes

2020-12-03 02:43 UTC, merged