Fix Invalid Resource Code Action Snippet issue
ballerina-platform/ballerina-lang pull request #28137
Opened 2021-01-22 15:02 UTC by xlight05

## Purpose
Fix Invalid Resource Code Action Snippet issue when resource name is not specified.

2021-01-24 07:51 UTC, rasika commented
@xlight05 Is there any git issue for this PR? If so, please attach it into the PR. Also shall we adhere the default PR template

2021-01-24 07:52 UTC, rasika requested changes
@xlight05 Is there any git issue for this PR? If so, please attach it into the PR. Also shall we adhere the default PR template

2021-01-25 03:18 UTC, xlight05 commented
> @xlight05 Is there any git issue for this PR? If so, please attach it into the PR. Also shall we adhere the default PR template
Sorry. Please check now.

2021-01-25 03:20 UTC, rasika approved these changes

2021-01-25 16:40 UTC, merged