Fix pull packages with snapshot versions
ballerina-platform/ballerina-lang pull request #28426
Opened 2021-02-03 09:53 UTC by pramodya1994

## Purpose
> Fixed issue happened when pulling packages with snapshot versions.
```
bal pull pramodya/sample:0.1.0-alpha
```

Fixes https://github.com/ballerina-platform/ballerina-lang/issues/28418

## Approach
> Removed validating full package name (`<org-name>/<package-name>:<version>`), and added seperate validations to validate org, package name and version.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-02-03 09:58 UTC, hevayo requested changes
Can we add some test cases

2021-02-03 10:41 UTC, pramodya1994 commented
> Can we add some test cases

I will add to distribution

2021-02-03 13:56 UTC, pramodya1994 commented
Added tests to distribution in https://github.com/ballerina-platform/ballerina-distribution/pull/1274

2021-02-05 07:02 UTC, hevayo approved these changes

2021-02-05 07:02 UTC, merged