Invalidate record rest descriptor inside open record
ballerina-platform/ballerina-lang pull request #28495
Opened 2021-02-08 12:13 UTC by rdulmina

## Purpose
$subject

Fixes #27340

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-02-08 16:56 UTC, lochana-chathura requested changes

2021-02-08 16:56 UTC, lochana-chathura commented on compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/parser/BallerinaParser.java
> +                        DiagnosticErrorCode.ERROR_OPEN_RECORD_CAN_NOT_CONTAIN_RECORD_REST_DESCRIPTOR);
This would give IndexOutofBoundException when there is no item in the list. 
e.g. 
```bal
type myRecord record {
    string...;
}; 
```

2021-02-08 16:56 UTC, lochana-chathura commented on compiler/ballerina-parser/src/main/java/io/ballerina/compiler/internal/diagnostics/DiagnosticErrorCode.java
> +    ERROR_OPEN_RECORD_CAN_NOT_CONTAIN_RECORD_REST_DESCRIPTOR("BCE666",
Let's use "cannot" here which is more common and is used in all other error codes.
```suggestion
    ERROR_OPEN_RECORD_CANNOT_CONTAIN_RECORD_REST_DESCRIPTOR("BCE666",
```

2021-02-09 09:59 UTC, lochana-chathura approved these changes
LGTM

2021-02-09 12:10 UTC, KRVPerera approved these changes

2021-02-09 12:17 UTC, merged