Fix table iterator error for configurables
ballerina-platform/ballerina-lang pull request #28719
Opened 2021-02-17 13:11 UTC by HindujaB

## Purpose
The issue happens when an Intersection type (`record & readonly`) is passed as a table constraint type when creating Table value. 
Fixes #28676 

## Approach
> Use runtime `TypeCreator` API to pass the readonly table type  for value creation. 

## Samples

## Remarks

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-02-18 05:36 UTC, warunalakshitha commented
LGTM

2021-02-23 10:35 UTC, HindujaB commented on bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigTomlParser.java
> +                TypeCreator.createTableType(((IntersectionType) constraintType).getEffectiveType(), keys, true);
Check the casts for the following cases as well 
```ballerina
type AuthInfo readonly & record {|
    readonly string username;
    int id = 100;
    ...
|};
```
And this 
```ballerina
type AuthInfo record {|
    readonly string username;
    readonly int id = 100;
    //all fields are readonly
|};
```

2021-03-04 08:21 UTC, HindujaB commented on bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigTomlParser.java
> -        validateRequiredField(initialValueEntries, effectiveType, variableName);
specialise the field read-only case to use mapValue API

2021-03-05 11:26 UTC, HindujaB commented on bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/configurable/ConfigTomlParser.java
> +            if (!SymbolFlags.isFlagOn(flag, SymbolFlags.OPTIONAL) && !SymbolFlags.isFlagOn(flag,
If a record with all `readonly` fields contains a defaultable field and the value is not provided at configuration, we throw an error.

2021-03-08 08:30 UTC, manuranga requested changes

2021-03-08 08:30 UTC, manuranga commented on tests/jballerina-integration-test/src/test/resources/configurables/configurableProject/main/main.bal
> +
Let's add a use case for no-fields-are-read-only record.

2021-03-09 03:21 UTC, manuranga submitted a review, later dismissed

2021-03-10 06:38 UTC, warunalakshitha approved these changes
LGTM

2021-03-10 09:38 UTC, merged