Update record field suggestion sorting order to prioritize record fields
ballerina-platform/ballerina-lang pull request #28844
Opened 2021-02-23 11:07 UTC by IMS94

## Purpose
$subject

Fixes #20313

## Approach
If a completion item is a `record field` or an `object field` while the node at cursor is a `field access`, we now show the record/object fields at the top of the list.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-02-25 03:42 UTC, nadeeshaan approved these changes

2021-02-25 03:42 UTC, nadeeshaan commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/FieldAccessContext.java
> +        super.sort(context, node, completionItems);
Here we traverse the completion item list twice. In this particular context we can traverse the list once and assign the priorities. or, in a more configurable way, we can add a sort API to the sorting utils to accept a priority offset and assign the priority a completion item by offsetting the default priority.

2021-02-25 03:43 UTC, nadeeshaan requested changes
Here we traverse the completion item list twice. In this particular context we can traverse the list once and assign the priorities. or, in a more configurable way, we can add a sort API to the sorting utils to accept a priority offset and assign the priority a completion item by offsetting the default priority.

2021-03-01 06:13 UTC, IMS94 commented
@nadeeshaan Updated the PR as we discussed in a meeting to use a utility method to get the rank of a completion item with an optional offset.

2021-03-02 04:04 UTC, nadeeshaan approved these changes
LGTM

2021-03-02 04:04 UTC, merged