Remove BLangCompilerException with a warning for invalid settings
ballerina-platform/ballerina-lang pull request #28960
Opened 2021-03-02 15:45 UTC by pramodya1994

This fix will Remove BLangCompilerException and display a warning when 'Settings.toml' is having syntax errors.
Ballerina package build will continue with a warning as shown below.

```
$ bal build
warning: invalid 'Settings.toml' due to Key is not followed by an equals sign on line 4: 353535

Compiling source
        pramodya/sample2:0.1.0

Running Tests

        sample2
        No tests found

Creating bala
        target/bala/pramodya-sample2-any-0.1.0.bala

Generating executable
        target/bin/sample2-0.1.0.jar
```

Fixes https://github.com/ballerina-platform/ballerina-lang/issues/28764

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues.

Fixes #<Issue Number>

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-03-02 15:57 UTC, hevayo commented
Can we add the settings.toml path to the warning so that users can find it easily.

2021-03-02 16:50 UTC, pramodya1994 commented
> Can we add the settings.toml path to the warning so that users can find it easily.

What do you think about following warning?
```
warning: invalid 'Settings.toml' file at:/Users/pramodya/.ballerina/Settings.toml due to:Key is not followed by an equals sign on line 4: 353535

2021-03-10 13:44 UTC, hevayo commented on compiler/ballerina-lang/src/main/java/org/ballerinalang/toml/parser/SettingsProcessor.java
> +            out.println("warning: invalid 'Settings.toml' file at:" + settingsPath + " due to:" + e.getMessage());
This output will break LS if invoked from Project API.

2021-03-10 13:45 UTC, hevayo requested changes
Please see inline

2021-04-06 10:46 UTC, pramodya1994 commented
We can ignore the toml parsing errors and continue the build, the Only exception is when the user has defined a proxy in the `Settings.toml`, and if there's a syntax error, Then we won't consider defined proxy when we set the remote repo.

@hevayo WDYT about this?

2021-04-15 08:54 UTC, hevayo requested changes
Can we add warning in a build command for invalid settings files

2021-04-16 09:35 UTC, hevayo approved these changes

2021-04-18 02:02 UTC, hevayo approved these changes

2021-04-18 02:03 UTC, merged