Fix issue in creating field symbols
ballerina-platform/ballerina-lang pull request #29383
Opened 2021-03-22 14:29 UTC by pubudu91

## Purpose
This PR fixes an issue there was in creating field symbols when the field's type is an undefined type.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-03-26 02:35 UTC, nadeeshaan commented
Shall we create an issue and tag in the PR?

2021-03-26 02:38 UTC, nadeeshaan requested changes

2021-03-26 02:38 UTC, nadeeshaan commented on tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/incompletesource/InvalidFieldTypeTest.java
> + * Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
Fix year

2021-03-26 05:34 UTC, pubudu91 commented
> Shall we create an issue and tag in the PR? Also, since we do not filter the fields now, does this means we are getting fields where their types can be `SemanticError`?

Issue is already linked (#29149). And yes, that can happen now.

2021-03-26 06:14 UTC, nadeeshaan commented
> > Shall we create an issue and tag in the PR? Also, since we do not filter the fields now, does this means we are getting fields where their types can be `SemanticError`?
> 
> Issue is already linked (#29149). And yes, that can happen now.

Showing the SemanticError as the type to the user might be misleading though. If we don't have a solution for that better if we can track it as a known issue

2021-03-26 06:36 UTC, pubudu91 commented
> > > Shall we create an issue and tag in the PR? Also, since we do not filter the fields now, does this means we are getting fields where their types can be `SemanticError`?
> > 
> > 
> > Issue is already linked (#29149). And yes, that can happen now.
> 
> Showing the SemanticError as the type to the user might be misleading though. If we don't have a solution for that better if we can track it as a known issue

We can skip the fields with semantic error for its type at the semantic API if needed. Either have to skip, or still make it visible with the error. So basically have to decide between having missing field symbols vs. having field symbols whose type is semantic error

2021-03-27 05:34 UTC, grainier approved these changes

2021-03-27 05:41 UTC, merged