Add 'exported' modules feature to project API
ballerina-platform/ballerina-lang pull request #29629
Opened 2021-03-26 09:16 UTC by pramodya1994

## Purpose
> $Title

Fixes https://github.com/ballerina-platform/ballerina-lang/issues/29274

## Approach
> If some bal file has an import to a non exported module, below diagnostic will be shown.
```
Compiling source
        pramodya/test_calculator:0.1.0
ERROR [main.bal:(2:1,2:39)] module calculator.mul is not an exported module
error: compilation contains errors
```

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-03-26 23:03 UTC, sameerajayasoma requested changes

2021-03-26 23:03 UTC, sameerajayasoma commented on compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
> +                                        null, "module '" + moduleName + "' is not an exported module",
Don't use null here, Please use a proper error code. This error code is shown in VSCode diagnostics. We don't want to show `null` to users.

2021-03-26 23:03 UTC, sameerajayasoma commented on compiler/ballerina-lang/src/main/java/io/ballerina/projects/PackageCompilation.java
> +            for (DocumentId documentId : module.documentIds()) {
This is an expensive loop. We are iterating through all the documents first and each import declaration in a document, then we iterate through all the dependencies of the current package. 

I think we need to find a better way to solve this.

2021-04-05 07:52 UTC, pramodya1994 commented
Added a new PR https://github.com/ballerina-platform/ballerina-lang/pull/29774

2021-04-05 07:52 UTC, closed without merging