Add Scheduler maximum thread pool size configuration to configurable variable
ballerina-platform/ballerina-lang pull request #30153
Opened 2021-04-22 09:25 UTC by HindujaB

## Purpose
Ballerina runtime provides configuration support for maximum thread pool size. 
It was earlier supported through environment variable `BALLERINA_MAX_POOL_SIZE` 

This PR moves this configuration to configurable variable `poolSize` from `lang.runtime` module

Now we can provide the scheduler thread pool size in the `Config.toml` as below,
```toml
[ballerina.lang.runtime]
poolSize = 16
```

Fixes #29729 

## Approach

## Samples

## Remarks

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [x] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-04-28 05:11 UTC, warunalakshitha commented on bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/api/constants/RuntimeConstants.java
> -    public static final String BALLERINA_MAX_POOL_SIZE_ENV_VAR = "BALLERINA_MAX_POOL_SIZE";
So with this change, we cannot set the pool size with env variable? There are some docs related to that. we might need to change those too.

2021-04-29 13:50 UTC, warunalakshitha commented
There are few docs uses env variable to set the pool size. You can find the usages https://github.com/search?p=1&q=org%3Aballerina-platform+BALLERINA_MAX_POOL_SIZE&type=Code

We can omit 1.x version docs. shall we create a doc issue.

2021-04-29 14:49 UTC, HindujaB commented
> There are few docs use env variable to set the pool size. You can find the usages https://github.com/search?p=1&q=org%3Aballerina-platform+BALLERINA_MAX_POOL_SIZE&type=Code
> 
> We can omit 1.x version docs. shall we create a doc issue?

Created https://github.com/ballerina-platform/ballerina-dev-website/issues/2147

2021-04-29 18:57 UTC, warunalakshitha commented on tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
> +    public void testSchedulerThreadPoolSize() throws BallerinaTestException {
I think this is not part of configuration tests. Shall we move to a separate class.

2021-04-29 18:59 UTC, warunalakshitha commented on tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
> +    public void testSchedulerThreadPoolSize() throws BallerinaTestException {
runtime.SchedulerConfigTest

2021-04-29 19:00 UTC, warunalakshitha commented on tests/jballerina-integration-test/src/test/java/org/ballerinalang/test/configurables/ConfigurableTest.java
> +    public void testSchedulerThreadPoolSize() throws BallerinaTestException {
Should we need 2 tests. 
1 warning and take the env value
2 take from configurable

2021-04-30 09:02 UTC, manuranga commented
1) The coding convent for final variable seems to upper case.
2) Shall we make the name bit more descriptive as well, how about `STRAND_THREAD_POOL_SIZE` ?
@sameerajayasoma @warunalakshitha  wtyt?

2021-05-03 06:49 UTC, hasithaa commented on compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
> +                                                Map.entry(Names.RUNTIME, this.langRuntimeModuleSymbol),
This is wrong. Please remove this.

2021-05-03 06:51 UTC, hasithaa commented on compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/model/SymbolTable.java
> +                                                Map.entry(Names.RUNTIME, this.langRuntimeModuleSymbol),
Ref: https://ballerina.io/ballerina-spec/spec.html#section_8.1

2021-05-03 06:52 UTC, hasithaa commented on langlib/lang.runtime/src/main/ballerina/runtime.bal
> +
See https://github.com/ballerina-platform/ballerina-spec/issues/838

2021-05-03 06:53 UTC, hasithaa requested changes
Need to fixed once we finalized https://github.com/ballerina-platform/ballerina-spec/issues/838

2021-05-04 04:42 UTC, closed without merging