[LS] Fix invalid iterator type resolution for foreach completion item issue
ballerina-platform/ballerina-lang pull request #30442
Opened 2021-05-07 13:58 UTC by malinthar

## Purpose
Fix the invalid iterator type rendered with foreach completion item rendered for iterable field access. 

Fixes #30438 

## Approach
Use `CommonUtils.getModifiedTypeName()` function

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-05-07 14:23 UTC, mohanvive approved these changes

2021-05-07 16:02 UTC, IMS94 approved these changes

2021-05-09 14:21 UTC, nadeeshaan requested changes
Please add a couple of test cases.
Consider a multi-module project

2021-05-10 04:06 UTC, malinthar commented
> Please add a couple of test cases.
> Consider a multi-module project

done

2021-05-10 09:06 UTC, merged