Migrate low code editor LS extensions to alpha5
ballerina-platform/ballerina-lang pull request #30503
Opened 2021-05-12 00:35 UTC by kaviththiranga

## Purpose
Includes several fixes to lang-server extensions for low code editor

Fixes #<Issue Number>

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-05-12 02:45 UTC, nadeeshaan requested changes

2021-05-12 02:45 UTC, nadeeshaan commented on compiler/ballerina-lang/src/main/java/module-info.java
> +    exports io.ballerina.compiler.api.impl.symbols;
It is not the intended usage to utilize the implementation classes. Instead we use the exposed public interfaces. I see that the reason to use the impl is to use `BallerinaUnionTypeSymbol` in `BallerinaSymbolServiceImpl.java`. Here we can use the `UnionTypeSymbol` which is the public interface. Hence shall we remove this export?

2021-05-12 02:45 UTC, nadeeshaan commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/visitor/UnusedSymbolsVisitor.java
> +        if (symbol.isPresent()) {
We can use early return here to simplify the nesting

2021-05-12 02:45 UTC, nadeeshaan commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/visitor/UnusedSymbolsVisitor.java
> +        if (annotationNodeSymbol.isPresent()) {
Shall we use early return here and line 213?

2021-05-12 02:45 UTC, nadeeshaan commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/symbol/BallerinaSymbolServiceImpl.java
> +import io.ballerina.compiler.api.impl.symbols.BallerinaUnionTypeSymbol;
This implementation class usage has been addressed in a comment above

2021-05-12 02:45 UTC, nadeeshaan commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/symbol/BallerinaSymbolServiceImpl.java
> +            if (!filePath.isPresent()) {
use `filePath.isEmpty()` instead

2021-05-12 02:45 UTC, nadeeshaan commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/symbol/BallerinaSymbolServiceImpl.java
> +                if (semanticModel.isPresent()) {
Using early return will be better if possible.

2021-05-17 04:27 UTC, nadeeshaan submitted a review, later dismissed
LGTM

2021-05-17 05:54 UTC, kaviththiranga commented
@NipunaMarcus seems we have PR check failures again

2021-05-19 04:36 UTC, nadeeshaan approved these changes
Low diff coverage and has to be addressed with #30660

2021-05-19 04:36 UTC, merged