[LS] Add foreach and typegurad  completion items  on nested field access
ballerina-platform/ballerina-lang pull request #30889
Opened 2021-05-31 09:53 UTC by malinthar

## Purpose
$subject

Fixes #30829 

## Samples

#### foreach statement

![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/35211477/120175497-e960a100-c223-11eb-8d3d-5cdc1e6f14fb.gif)

#### typeguard statement

![ezgif com-gif-maker](https://user-images.githubusercontent.com/35211477/120175516-ed8cbe80-c223-11eb-98c4-0e7e82e259ae.gif)

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-06-01 03:55 UTC, nadeeshaan requested changes

2021-06-01 03:55 UTC, nadeeshaan commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ForeachCompletionUtil.java
> +                symbolName = "items";
What is the use-case of "items" here?

2021-06-01 03:55 UTC, nadeeshaan commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/TypeGuardCompletionUtil.java
> +                symbolName = "name";
what is the use-case for this?

2021-06-01 04:15 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/TypeGuardCompletionUtil.java
> +                symbolName = "name";
no particular use case. I'll remove it.

2021-06-03 06:28 UTC, nadeeshaan approved these changes
LGTM

2021-06-03 06:28 UTC, merged