Remove unused dependency
ballerina-platform/ballerina-lang pull request #31409
Opened 2021-06-23 14:37 UTC by udda1996

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues.

Fixes #<Issue Number>

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-06-23 18:10 UTC, pubudu91 requested changes
A couple of points,
- Please pay attention to formatting. There are unnecessary new lines added in files through out the PR.
- Pay attention to commits and commit messages. Most of the commits seem like temporary or duplicate commits made during development. Group the commits appropriately and squash the rest. 
- Look in to rebasing instead of merging when syncing with the upstream branch. That'd help avoid the multiple merge commits scattered throughout the PR. Also would make it easier if/when you want to edit previous commits.
- If removing something, let's remove it instead of commenting it out.

2021-06-24 04:58 UTC, keizer619 commented on build.gradle
> +
```suggestion
```

2021-06-24 04:58 UTC, keizer619 commented on bvm/ballerina-runtime/build.gradle
> +
```suggestion
```

2021-06-24 04:59 UTC, keizer619 commented on cli/central-client/build.gradle
> +//    implementation 'javax.ws.rs:javax.ws.rs-api'
```suggestion
```

2021-06-24 04:59 UTC, keizer619 commented on tests/ballerina-test-utils/build.gradle
> +//    implementation 'org.apache.ws.commons.axiom:axiom-dom'
```suggestion
```

2021-06-24 04:59 UTC, keizer619 commented on tests/jballerina-integration-test/src/test/resources/identifier/ModuleNameClashProject/Dependencies.toml
> +
```suggestion
```

2021-06-24 05:00 UTC, keizer619 commented on tests/jballerina-integration-test/src/test/resources/observability/metrics_tests/Dependencies.toml
> +
```suggestion
```

2021-06-24 05:00 UTC, keizer619 commented on tests/jballerina-integration-test/src/test/resources/observability/tracing_tests/Dependencies.toml
> +
```suggestion
```

2021-06-24 05:00 UTC, keizer619 commented on tests/observability-test-utils/src/test/resources/listener_tests/Dependencies.toml
> +
```suggestion
```

2021-06-24 08:15 UTC, closed without merging