Add 'Implement all' code action
ballerina-platform/ballerina-lang pull request #31477
Opened 2021-06-28 18:12 UTC by TharushiJay

## Purpose
$subject to implement all methods in one code action.

![1](https://user-images.githubusercontent.com/27485094/123643064-a3f2bc00-d841-11eb-920c-cbdacf87e35a.gif)

Fixes #30749

## Samples
Supports the same for,

1) Object constructor expressions
![Screenshot from 2021-06-28 23-06-02](https://user-images.githubusercontent.com/27485094/123680215-12e20c00-d866-11eb-8749-fe4180632f7f.png)

2) Object types
![Screenshot from 2021-06-28 23-09-36](https://user-images.githubusercontent.com/27485094/123680188-09f13a80-d866-11eb-8a3b-07ceb64df1dc.png)

3) Service declarations
![Screenshot from 2021-06-28 23-06-25](https://user-images.githubusercontent.com/27485094/123680256-1d040a80-d866-11eb-80e1-0c3565b4de33.png)

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-06-29 04:57 UTC, IMS94 requested changes
We have to introduce an intermediate code action provider common to `ImplementAllCodeAction` and `ImplementMethodCodeAction`. Something like `AbstractImplementMethodCodeAction` which extends `AbstractCodeActionProvider`.

2021-06-30 10:44 UTC, IMS94 requested changes
Overall looks good. Need 2 modifications.

2021-06-30 10:44 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ImplementAllCodeAction.java
> +        List<TextEdit> edits = new ArrayList<>(importsAcceptor.getNewImportTextEdits());
We don't need the imports acceptor here right?

2021-06-30 10:44 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AbstractImplementMethodCodeAction.java
> +public abstract class AbstractImplementMethodCodeAction extends AbstractCodeActionProvider {
We can't have this annotation here

2021-07-01 08:29 UTC, malinthar submitted a review, later dismissed
LGTM

2021-07-06 06:11 UTC, nadeeshaan commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AbstractImplementMethodCodeAction.java
> +    protected static final Set<String> DIAGNOSTICCODES = Set.of(
Use `DIAGNOSTIC_CODES`

2021-07-06 06:33 UTC, nadeeshaan requested changes

2021-07-06 06:33 UTC, nadeeshaan commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/AbstractImplementMethodCodeAction.java
> +     */
Fix the formatting here

2021-07-06 06:34 UTC, nadeeshaan commented
Here, when we are generating a function with a return, shall we try to include the return statement as well? Otherwise there is a semantic error in the generated code segment.

2021-07-07 03:29 UTC, nadeeshaan approved these changes
LGTM

2021-07-07 04:30 UTC, IMS94 approved these changes
LGTM!

2021-07-07 04:40 UTC, merged

2021-07-07 05:26 UTC, TharushiJay commented
> Here, when we are generating a function with a return, shall we try to include the return statement as well? Otherwise there is a semantic error in the generated code segment.

Created issue #31608 for this.