Recognize Enum in Recursive Array Type
ballerina-platform/ballerina-lang pull request #31488
Opened 2021-06-29 08:00 UTC by sanjana

## Purpose
> $title

Fixes #30034

## Approach
> 

## Samples
> 

## Remarks
> 

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-06-29 08:28 UTC, pubudu91 requested changes
Let's add a few tests to address this. Also is this issue applicable for constants as well?

2021-06-30 04:05 UTC, KRVPerera commented on compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
> +                        referredType.tag == TypeTags.FINITE || (referredType.tag == TypeTags.UNION &&
It is enough to add `referredType.tag == TypeTags.UNION` here. But this whole condition is not optimum. Ideally 
`referredType != symTable.semanticError && referredType != symTable.noType` kind of logic should work right.

2021-06-30 18:09 UTC, KRVPerera commented on compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/SymbolEnter.java
> +                        referredType.tag == TypeTags.FINITE || (referredType.tag == TypeTags.UNION &&
Check this also https://github.com/ballerina-platform/ballerina-lang/issues/30101#issuecomment-863888227

2021-07-06 08:42 UTC, pubudu91 approved these changes

2021-07-06 08:43 UTC, merged