Fix field symbol position issue in intersected record types
ballerina-platform/ballerina-lang pull request #31968
Opened 2021-07-30 12:17 UTC by pubudu91

## Purpose
This PR fixes the incorrect position given for record fields of an intersected record type.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-08-02 04:18 UTC, sanjana requested changes

2021-08-02 04:18 UTC, sanjana commented on tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/FieldSymbolTest.java
> +        Location symbolPos = fieldSymbol.getLocation().get();
```suggestion
        assertTrue(fieldSymbol.getLocation().isPresent());
        Location symbolPos = fieldSymbol.getLocation().get();
```

Missing a presence check here.

2021-08-02 10:16 UTC, pubudu91 commented on tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/FieldSymbolTest.java
> +        Location symbolPos = fieldSymbol.getLocation().get();
Addressed with 0ab4473

2021-08-03 05:59 UTC, sanjana approved these changes
LGTM

2021-08-03 06:12 UTC, mohanvive approved these changes

2021-08-03 06:12 UTC, merged