Fix symbol owner bug in union type symbols when it's read from BIR
ballerina-platform/ballerina-lang pull request #32600
Opened 2021-09-07 08:03 UTC by pubudu91

## Purpose
This PR fixes an issue in `BIRPackageSymbolEnter` in reading union type symbols. There, the created type symbol's owner was set incorrectly.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-09-07 08:36 UTC, KRVPerera approved these changes

2021-09-07 11:12 UTC, sanjana requested changes

2021-09-07 11:12 UTC, sanjana commented on tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/SymbolOwnerTest.java
> +        Optional<ModuleSymbol> module = symbol.get().getModule();
Wouldn't it be better to add a `Assert.assertTrue(symbol.isPresent());` check here as well?

2021-09-07 12:17 UTC, pubudu91 commented
@nadeeshaan @IMS94 Please note the changes to the LS completion test cases.

2021-09-07 12:30 UTC, KRVPerera approved these changes

2021-09-08 04:49 UTC, IMS94 submitted a review, later dismissed
LGTM!

2021-09-08 08:42 UTC, IMS94 approved these changes

2021-09-08 08:44 UTC, merged