Add spec conformance tests for module level declaration and annotations
ballerina-platform/ballerina-lang pull request #32763
Opened 2021-09-15 13:25 UTC by dulajdilshan

## Purpose
$title

Fixes #32664

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-09-23 08:10 UTC, sanjana requested changes

2021-09-23 08:10 UTC, sanjana commented on tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ConstDeclSymbolTest.java
> +        }
```suggestion
        assertTrue(symbol.documentation().isPresent());
        Documentation fieldDocs = symbol.documentation().get();
        if (expDoc != null) {
            assertTrue(fieldDocs.description().isPresent());
            assertEquals(fieldDocs.description().get(), expDoc);
        } else {
            assertFalse(fieldDocs.description().isPresent());
        }
```

Wouldn't this be a better optimization?

2021-09-23 08:10 UTC, sanjana commented on tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/EnumDeclSymbolTest.java
> +        }
Ditto

2021-09-23 08:10 UTC, sanjana commented on tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/EnumDeclSymbolTest.java
> +        }
Ditto

2021-09-23 08:10 UTC, sanjana commented on tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/VarDeclSymbolTest.java
> +        }
Ditto

2021-09-28 13:01 UTC, pubudu91 commented on tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/XMLNamespaceDeclSymbolTest.java
> +
Shall we get rid of these new lines at the top?

2021-09-28 13:26 UTC, pubudu91 commented on tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/enum_decl_symbol_test.bal
> +    OTHER
Shall we change one of these so that the RHS expr is a const ref? And test whether the correct symbol is returned for such cases?

2021-09-28 13:31 UTC, pubudu91 commented on tests/ballerina-compiler-api-test/src/test/resources/test-src/symbols/xmlns_decl_symbol_test.bal
> +xmlns uri as ex;
The following case should also be tested.
```ballerina
xmlns <cursor>uri as ex;
```

2021-10-04 05:58 UTC, mohanvive approved these changes

2021-10-04 08:52 UTC, sanjana approved these changes
LGTM

2021-10-05 08:03 UTC, sanjana requested changes

2021-10-05 08:03 UTC, sanjana commented on tests/ballerina-compiler-api-test/src/test/java/io/ballerina/semantic/api/test/symbols/ConstDeclSymbolTest.java
> +            assertEquals(fieldAnnots.get(0).getName().get(), expAnnot);
`assertTrue(fieldAnnots.get(0).getName().isPresent());`

Wouldn't this be better to have?

2021-10-06 06:18 UTC, mohanvive approved these changes

2021-10-06 06:18 UTC, merged