Fix projectRoot path resolve issue with plugin tree view
ballerina-platform/ballerina-lang pull request #32968
Opened 2021-09-29 10:56 UTC by prabushi

## Purpose
Skip the project root path resolve flow by providing the current document identifier to avoid the projectRoot path resolve issue on the project API.

Fixes https://github.com/ballerina-platform/ballerina-lang/issues/32954

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-09-29 10:59 UTC, IMS94 approved these changes
LGTM!

2021-09-29 11:38 UTC, IMS94 requested changes
I was thinking, though the project returned `Optional.empty()`, tests passed because the validations we do on the returned components aren't enough. If not now, it'll be better to add more validations to the returned components.

2021-09-29 11:38 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/packages/BallerinaPackageServiceImpl.java
> +            Module module = project.get().currentPackage().module(moduleId);
Can we do `currentPackage.module()` since we already have the `currentPackage`.

2021-09-29 16:43 UTC, prabushi commented
> I was thinking, though the project returned `Optional.empty()`, tests passed because the validations we do on the returned components aren't enough. If not now, it'll be better to add more validations to the returned components.
Added an assert for the package count to avoid test skip.

2021-09-30 03:25 UTC, IMS94 approved these changes

2021-09-30 07:48 UTC, merged