Fix completion sorting in remote method calls
ballerina-platform/ballerina-lang pull request #33797
Opened 2021-11-12 12:56 UTC by IMS94

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues.

Fixes #33625
Fixes #33672

## Approach
Updated `ContextTypeResolver`

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-11-15 04:10 UTC, malinthar requested changes
Changes look good!

2021-11-15 04:10 UTC, malinthar commented on language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/ActionNodeContextTest.java
> +//        return new Object[][]{
Shall we remove these lines

2021-11-15 08:28 UTC, IMS94 commented on language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/ActionNodeContextTest.java
> +//        return new Object[][]{
Done. It was a mistake.

2021-11-15 16:22 UTC, IMS94 commented
@nadeeshaan @malinthar @mohanvive With this PR, I have updated the assignability check as follows:
1. Items which are directly assignable to the context are sorted first
2. Items which are assignable after adding a `check` expression are sorted 2nd - This is similar to considering the `edit distance`. When we write code, we usually do `int varName = clientObj->methodCall()` and then add the `check` in between. That's why I thought of using this idea. Since remote method calls usually comes with an error union, this should be very useful.
3. Other items are sorted 3rd

WDYT?

2021-11-15 16:29 UTC, nadeeshaan commented
> @nadeeshaan @malinthar @mohanvive With this PR, I have updated the assignability check as follows:
> 
> 1. Items which are directly assignable to the context are sorted first
> 2. Items which are assignable after adding a `check` expression are sorted 2nd - This is similar to considering the `edit distance`. When we write code, we usually do `int varName = clientObj->methodCall()` and then add the `check` in between. That's why I thought of using this idea. Since remote method calls usually comes with an error union, this should be very useful.
> 3. Other items are sorted 3rd
> 
> WDYT?

This is very good thinking @IMS94.  We do sort within the items related check as well right?

2021-11-16 03:48 UTC, IMS94 commented
> This is very good thinking @IMS94. We do sort within the items related check as well right?
@nadeeshaan yes, as of now we do default sorting within each group (mentioned above). Depending on the context, we can customize that as well.

2021-11-16 11:03 UTC, nadeeshaan approved these changes
LGTM

2021-11-22 10:19 UTC, mohanvive approved these changes

2021-11-22 10:20 UTC, mohanvive commented
> Changes look good!

@malinthar Need your approval to merge the PR.

2021-11-22 10:57 UTC, malinthar approved these changes
LGTM!

2021-11-22 11:01 UTC, merged