Stage slbeta4 sync
ballerina-platform/ballerina-lang pull request #33957
Opened 2021-11-23 11:57 UTC by azinneera

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues.

Fixes #<Issue Number>

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2021-11-24 06:57 UTC, MaryamZi requested changes
Need to revert https://github.com/ballerina-platform/ballerina-lang/pull/33967/commits/9583fc5c4fac5e7bd30681547251f5ed910053e9 before we merge this PR.

2021-11-24 15:50 UTC, MaryamZi commented
> Need to revert [9583fc5](https://github.com/ballerina-platform/ballerina-lang/commit/9583fc5c4fac5e7bd30681547251f5ed910053e9) before we merge this PR.

Done in https://github.com/ballerina-platform/ballerina-lang/pull/33975.

2021-11-25 00:25 UTC, MaryamZi commented on .github/workflows/publish_timestamped_release.yml
> +      - stage-slbeta4
```suggestion
```

2021-11-25 00:25 UTC, MaryamZi commented on .github/workflows/pull_request_ubuntu_build.yml
> +      - stage-slbeta4
```suggestion
```

2021-11-25 00:25 UTC, MaryamZi commented on .github/workflows/pull_request_windows_build.yml
> +      - stage-slbeta4
```suggestion
```

2021-11-25 03:32 UTC, MaryamZi approved these changes

2021-11-25 05:59 UTC, MaryamZi approved these changes
Front-end conflict resolving changes were reviewed via the individual PRs.

2021-11-25 06:04 UTC, nadeeshaan approved these changes

2021-11-25 06:11 UTC, NipunaRanasinghe approved these changes

2021-11-25 06:19 UTC, pcnfernando approved these changes

2021-11-25 06:19 UTC, azinneera commented
LGTM

2021-11-25 06:20 UTC, lochana-chathura approved these changes

2021-11-25 06:23 UTC, Dilhasha approved these changes

2021-11-25 06:27 UTC, DamithaSenevirathne approved these changes

2021-11-25 06:33 UTC, merged