Remove observability components
ballerina-platform/ballerina-lang pull request #34507
Opened 2022-01-05 04:27 UTC by LakshanKarunathilake

## Purpose
> Move observability components for separate components

- module-ballerina-observe ( as a standard library )
- module-ballerinai-observe

## Related Issues
- https://github.com/ballerina-platform/ballerina-lang/issues/33195

## Approach
> Moving observe lib components, observability test-utils and integration tests for separate repositories. Integration tests and observability-test-utils are moven to module-ballerinai-observe

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-01-06 18:52 UTC, nadundesilva commented on cli/ballerina-cli/src/main/resources/new_cmd_defaults/manifest-app.toml
> +observabilityIncluded = false
This shouldn't be changed as this is the new command's template.

2022-01-06 18:52 UTC, nadundesilva commented on cli/ballerina-cli/src/main/java/io/ballerina/cli/cmd/CommandUtil.java
> +        Files.writeString(balTomlPath, "\nobservabilityIncluded = false\n", StandardOpenOption.APPEND);
This shouldn't change as well as this is also a command output.

2022-01-06 18:57 UTC, nadundesilva commented
I think there should be a few more occurances of the config (`observabilityIncluded=true`)

2022-01-07 04:43 UTC, LakshanKarunathilake commented on gradle/javaLibsProject.gradle
> +//    dist project(':ballerina-observability-internal')
Fixed with https://github.com/ballerina-platform/ballerina-lang/pull/34507/commits/6bd61a0e2773eb36a25216ba7e42f6237a44658e

2022-01-07 06:57 UTC, nadundesilva commented on project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBuildProject.java
> +                "observabilityIncluded = false\n" +
Let's revert this and the assertion below.

2022-01-07 06:58 UTC, nadundesilva commented on project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBuildProject.java
> +        Assert.assertFalse(project.buildOptions().observabilityIncluded());
We can revert this by reverting `project-api/project-api-test/src/test/resources/projectWithBuildOptions/Ballerina.toml`

2022-01-07 06:58 UTC, nadundesilva commented on project-api/project-api-test/src/test/java/io/ballerina/projects/test/TestBuildProject.java
> +        Assert.assertFalse(project.buildOptions().observabilityIncluded());
Same as other assertion. (can revert this by reverting `project-api/project-api-test/src/test/resources/projectWithBuildOptions/Ballerina.toml`)

2022-01-10 06:06 UTC, warunalakshitha requested changes
We have an observability codegen in jballerina backend. So how are we going to test changes to codegen inside ballerina-lang since we move observe tests to the different repo?

Should we use the compiler plugin and move that code to observe stdlib?

2022-01-10 06:06 UTC, warunalakshitha commented
Unit test changes are LGTM

2022-01-10 06:09 UTC, nadundesilva commented
Is there a way to use a Compiler Plugin to make changes at BIR level ? 🤔 If not, we can't move that logic out of ballerina-lang.

2022-01-10 06:10 UTC, hasithaa commented
If we are going to keep the code-gen part, we need to keep test cases as well.

2022-01-10 06:16 UTC, nadundesilva commented
Yeah but test cases can't be run since `ballerinai/observe` package is needed to start observability. And `ballerina/observe` is required by `ballerinai/observe`.

If we are to keep the current integration test cases, we need to keep the two modules within ballerina-lang. Or else we need to write new tests only covering the BIR instrumentation.

2022-01-10 06:34 UTC, warunalakshitha commented
AFAIK we cannot test observability bir instrumentation since it just run before jvm codegen which will not be part of bir.

2022-01-11 05:33 UTC, warunalakshitha approved these changes
Please add an issue for track whether we can add some tests in lang with dummy module

2022-01-11 07:48 UTC, nadundesilva commented
Created an issue to track creating the `ballerinai/observe` dummy module and enabling test cases

2022-01-11 10:10 UTC, nadundesilva approved these changes

2022-01-12 05:13 UTC, hasithaa approved these changes

2022-01-12 05:13 UTC, merged