Modify treegen to allow "createdYear" in new node license header
ballerina-platform/ballerina-lang pull request #35408
Opened 2022-03-10 07:39 UTC by lochana-chathura

## Purpose
$subject.

Fixes #31047 

## Approach
- Add `createdYear` property to `syntax_tree_descriptor.json`. In absence of specification, it is defaulted to "2020". 
- `{{createdYear}}` variable was only introduced to `internal_node_template.mustache` & `external_node_template.mustache`
as other template license headers are not impacted on new node creation.

## Samples
To test, add the following to [syntax_tree_descriptor.json](https://github.com/ballerina-platform/ballerina-lang/blob/master/compiler/ballerina-treegen/src/main/resources/syntax_tree_descriptor.json) and run `./gradlew treegen`.
```json
        {
            "name": "SpreadMemberNode",
            "base": "Node",
            "kind": "SPREAD_MEMBER",
            "createdYear": "2022",
            "attributes": [
                {
                    "name": "ellipsis",
                    "type": "Token"
                },
                {
                    "name": "expression",
                    "type": "ExpressionNode"
                }
            ]
        }
```
To test the default behavior you can remove the `"createdYear": "2022"` property.

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-03-10 22:54 UTC, sameerajayasoma requested changes
I am not sure whether mixing year with the syntactic structure of a node. two different concerns IMO.

2022-03-11 03:06 UTC, hasithaa commented
I also agree with Sameera's point. Going forward, adding new nodes is rare. So after generating the nodes, We can update Licenses headers, before pushing the code.

2022-03-11 04:15 UTC, lochana-chathura commented
Agreed on point on mixing the year.

> So after generating the nodes, We can update Licenses headers, before pushing the code.

Currently, treegen re-writes all the nodes(including existing ones). So if we go forward with manually updating the license header, then the diff after executing `./gradlew treegen` will grow over time, as we add new nodes. Yeah. since adding nodes is rare this is not going to be an immediate problem or may never reach an unbearable level.

However, we can keep the year information separately, so that the `./gradlew treegen` output will always be in line with the actual one?

2022-03-11 10:22 UTC, rdulmina commented
> Agreed on point on mixing the year.
> 
> > So after generating the nodes, We can update Licenses headers, before pushing the code.
> 
> Currently, treegen re-writes all the nodes(including existing ones). So if we go forward with manually updating the license header, then the diff after executing `./gradlew treegen` will grow over time, as we add new nodes. Yeah. since adding nodes is rare this is not going to be an immediate problem or may never reach an unbearable level.
> 
> However, we can keep the year information separately, so that the `./gradlew treegen` output will always be in line with the actual one?

I think keeping a separate file to store year info the best and the easiest approach

2022-03-14 05:12 UTC, lochana-chathura commented
Closing temporarily as this was not originally planned for the sprint. 
I will revisit considering the suggestions.

2022-03-14 05:12 UTC, closed without merging