Add create record and extract type code actions
ballerina-platform/ballerina-lang pull request #35529
Opened 2022-03-22 15:57 UTC by IMS94

## Purpose
$subject

Fixes #35333
Fixes #32093

## Samples
![extract_type_codeaction](https://user-images.githubusercontent.com/11285165/159522314-68eb38b9-3259-4ad3-bafa-b6dfa3812787.gif)

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-03-24 05:07 UTC, malinthar requested changes

2022-03-24 05:07 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractTypeCodeAction.java
> +    private static String generateTypeName(String prefix, Set<String> visibleSymbolNames) {
Shall we add this method  or reuse one of the methods in CommonUtil to generate the type name
https://github.com/ballerina-platform/ballerina-lang/blob/02411da0cf01ac4f76c768ed911728b0e0ad115b/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java#L718

2022-04-07 03:14 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateTypeCodeAction.java
> +        Range range = new Range(CommonUtil.toPosition(tlNode.lineRange().startLine()),
Agreed. +1. Will come up with a way.

2022-04-27 04:55 UTC, malinthar reviewed
LGTM! Some minor version changes

2022-04-27 04:55 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateTypeCodeAction.java
> + * @since 2201.0.3
Version should be changed to 2201.1.1 ?

2022-04-27 04:55 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractTypeCodeAction.java
> + * @since 2201.0.3
Version

2022-04-27 04:55 UTC, malinthar commented on language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateTypeCodeActionTest.java
> + * @since 2201.0.x
version

2022-04-27 04:55 UTC, malinthar commented on language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/ExtractTypeCodeActionTest.java
> + * @since 2201.0.x
Version

2022-04-27 04:59 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/CreateTypeCodeAction.java
> + * @since 2201.0.3
Yes. Done!

2022-04-27 05:04 UTC, malinthar approved these changes
LGTM!

2022-04-27 05:15 UTC, merged