Show types coming from already imported modules in completions
ballerina-platform/ballerina-lang pull request #35785
Opened 2022-04-11 11:37 UTC by mindula

## Purpose
This PR shows types coming from already imported modules in completions.

Fixes #29840

## Samples
![Screenshot from 2022-04-11 17-03-52](https://user-images.githubusercontent.com/61020198/162731406-43f851ff-f135-4397-a86e-1ada3493915c.png)

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-04-27 06:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ballerina-platform/ballerina-lang?pullRequest=35785) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/ballerina-platform/ballerina-lang?pullRequest=35785) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: mindula<br/>:x: Mindula Rowel<br/><hr/>**Mindula Rowel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ballerina-platform/ballerina-lang?pullRequest=35785) it.</sub>

2022-05-17 09:25 UTC, gayalkuruppu requested changes

2022-05-17 09:25 UTC, gayalkuruppu commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/SearchProvider.java
> +public class SearchProvider {
How about CompletionSearchProvider? @mindula @IMS94

2022-05-17 09:25 UTC, gayalkuruppu commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/SearchProvider.java
> + * @since 2201.1.0
Change to 2201.1.1

2022-05-17 09:25 UTC, gayalkuruppu commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/Trie.java
> + * Filter completion items using Trie data structure.
Since this is a common data structure we can generalize it by removing `completion` from the desc

2022-05-17 09:25 UTC, gayalkuruppu commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/Trie.java
> + * @since 2201.1.0
Change the version to 2201.1.1

2022-05-19 04:37 UTC, mindula commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/SearchProvider.java
> +public class SearchProvider {
+1

2022-05-26 10:27 UTC, mindula commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/SearchProvider.java
> + * @since 2201.1.0
Done

2022-05-26 10:27 UTC, mindula commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/Trie.java
> + * @since 2201.1.0
Done

2022-06-08 09:15 UTC, malinthar requested changes

2022-06-08 09:15 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java
> +                }
```suggestion
                String moduleName = importDeclarationNode.prefix().isEmpty()? moduleSymbol.id().moduleName() : importDeclarationNode.prefix().get().prefix().value()
                    completionItem.setInsertText(moduleName + ":" + insertText);
                    completionItem.setLabel(moduleName + ":" + label);
```

2022-06-08 11:19 UTC, mindula commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
> +    public static List<Symbol> filterCompletionItemsByPrefix(List<Symbol> symbolList,
Done

2022-06-08 12:26 UTC, IMS94 requested changes

2022-06-08 12:26 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java
> +                completionItems.add(0, lsCompletionItem);
Is there a specific reason to add the item to `0`th index?

2022-06-08 17:16 UTC, mindula commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/utils/CommonUtil.java
> +    public static List<Symbol> filterSymbolsByPrefix(List<Symbol> symbolList,
Done

2022-06-10 17:04 UTC, malinthar approved these changes
LGTM!

2022-06-10 18:37 UTC, IMS94 approved these changes

2022-06-10 18:39 UTC, merged