Fix signature help and code action issues
ballerina-platform/ballerina-lang pull request #35999
Opened 2022-05-03 08:50 UTC by IMS94

## Purpose

Resending #35875 with some refactoring

Fixes https://github.com/ballerina-platform/ballerina-lang/issues/20314
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/35317
Fixes https://github.com/ballerina-platform/ballerina-lang/issues/35721

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-05-03 10:22 UTC, mindula commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/ParameterInfoModel.java
> + */
Shall we add the since tag?

2022-05-03 18:37 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/ParameterInfoModel.java
> + */
Done!

2022-05-05 02:09 UTC, malinthar requested changes
Some minor change requests

2022-05-05 02:09 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/Parameter.java
> +        if (this.isRestArg && !"".equals(type)) {
```suggestion
        if (this.isRestArg && !type.isEmpty()) {
```

2022-05-05 02:09 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/signature/Parameter.java
> +            if (type.contains("[]")) {
```suggestion
            if (type.endsWith("[]")) {
```

2022-05-05 04:05 UTC, malinthar approved these changes
LGTM!

2022-05-05 04:41 UTC, merged