Add documentation endpoint to lang-server
ballerina-platform/ballerina-lang pull request #36027
Opened 2022-05-04 16:36 UTC by sachiniSam

## Purpose
With this pr, a new endpoint is added to get the documentation that is needed for the Statement-editor in low-code-editor.
Related to the issue https://github.com/wso2-enterprise/internal-support-ballerina/issues/73

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-05-05 07:40 UTC, IMS94 requested changes
Can't we use `textDocument/hover` or `HoverUtil` in LS to get the required documentation instead of duplicating a seemingly similar use case?

2022-05-05 07:40 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/symbol/SymbolDocumentation.java
> +    public SymbolDocumentation(Optional<Documentation> documentation, List<ParameterInfo> parameters,
Using optional as a parameter is a bad practice. Instead we can overload the constructor with and without documentation parameter.

2022-05-05 07:40 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/symbol/SymbolDocumentation.java
> +    public static class ParameterInfo {
Can we reuse `org.ballerinalang.langserver.signature.Parameter`and `ParameterInfoModel` used in signature help of LS instead?

2022-05-06 11:07 UTC, sachiniSam commented
> Can't we use `textDocument/hover` or `HoverUtil` in LS to get the required documentation instead of duplicating a seemingly similar use case? If required, we can have an offline discussion on this.

As discussed offline, one of the main requirement from the low-code-editor is to get the parameter information and to separately render based on the type. (With the Statement editor user will be able to pick on which parameters to be selected).
With  `textDocument/hover` we get this info in a string which is not very scalable to extract each of these details separately. Therefore this endpoint is added to get the details in the required format

2022-05-12 06:22 UTC, malinthar requested changes

2022-05-12 06:22 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/symbol/BallerinaSymbolService.java
> +                if (!deprecatedParamMap.isEmpty()) {
We can remove this if condition

2022-05-12 06:22 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/symbol/BallerinaSymbolService.java
> +                        parameterMap().size());
What if the documentation of a particular parameter is missing? Wouldn't we get an exception when we try to add new SymbolDocumentation.PramaterInfo entry for that parameter in line 179?

2022-05-12 06:22 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/symbol/BallerinaSymbolService.java
> +                                    parameterSymbol.getName().get(),
Can there be instances where the name would be empty?

2022-05-12 06:22 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/symbol/BallerinaSymbolService.java
> +                                    documentation.get().parameterMap().get(parameterSymbol.getName().get()),
documentation.get().parameterMap().get(parameterSymbol.getName().get()) can return `null` in some cases. Shall we verify this using a filter

2022-05-12 10:17 UTC, malinthar submitted a review, later dismissed
LGTM!

2022-05-18 08:42 UTC, closed without merging