Implement semantic api related visitors for BLangListConstructorSprea…
ballerina-platform/ballerina-lang pull request #36076
Opened 2022-05-10 06:19 UTC by lochana-chathura

## Purpose
$subject.

Fixes #36073 

## Approach
N/A

## Samples
N/A

## Remarks
N/A

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-05-10 06:29 UTC, lochana-chathura commented
@dulajdilshan @sanjana Do we have semantic api tests for each AST node? Do we need to add test cases with these changes?

2022-05-10 06:35 UTC, sanjana commented
> @dulajdilshan @sanjana Do we have semantic api tests for each AST node? Do we need to add test cases with these changes?

@lochana-chathura, 
Need to add a test case for the `references()` in Semantic API for the crashing example mentioned in the related issue.

2022-05-10 07:58 UTC, lasinicl approved these changes

2022-05-10 09:14 UTC, pcnfernando commented
Try to handle the uncovered test scenarios for SemanticApi and QueryDesugar

2022-05-10 09:14 UTC, pcnfernando approved these changes

2022-05-10 09:21 UTC, sanjana requested changes

2022-05-10 09:21 UTC, sanjana commented on tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_var_ref_in_exprs.bal
> +
Superfluous new line. 
```suggestion
```

2022-05-10 09:21 UTC, sanjana commented on tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_var_ref_in_exprs.bal
> +
Ditto
```suggestion
```

2022-05-10 09:21 UTC, sanjana commented on tests/ballerina-compiler-api-test/src/test/resources/test-src/find-all-ref/find_var_ref_in_exprs.bal
> +
Ditto
```suggestion
```

2022-05-10 09:21 UTC, sanjana commented on tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_at_cursor_basic_test.bal
> +
Ditto
```suggestion
```

2022-05-10 09:21 UTC, sanjana commented on tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_at_cursor_basic_test.bal
> +
Ditto
```suggestion
```

2022-05-10 09:21 UTC, sanjana commented on tests/ballerina-compiler-api-test/src/test/resources/test-src/symbol_at_cursor_basic_test.bal
> +
Ditto
```suggestion
```

2022-05-10 09:37 UTC, malinthar approved these changes
LGTM!

2022-05-10 09:37 UTC, malinthar commented on language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/list_constructor_ctx_source5.bal
> +    int[] y = [...];
We have to fix the sorting of the completions at the cursor position after `...`. Further, we may have to add a spread op completion item as well (Just like spread field completion item for mapping constructors). Will create a separate issue for this.

2022-05-10 11:05 UTC, sanjana approved these changes
LGTM

2022-05-10 11:07 UTC, IMS94 approved these changes

2022-05-10 11:10 UTC, merged

2022-05-20 07:07 UTC, malinthar commented on language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/list_constructor_ctx_source5.bal
> +    int[] y = [...];
https://github.com/ballerina-platform/ballerina-lang/issues/35507 tracks the changes to be made