Fix capability setters not being detected for several extended language server services
ballerina-platform/ballerina-lang pull request #36451
Opened 2022-06-07 04:06 UTC by IMS94

## Purpose
$subject

Fixes #36448

## Approach
Implemented services were not registered in `META-INF/services` folder under `resources`. This caused those services to not be detected by LS during runtime.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-06-07 04:38 UTC, prabushi submitted a review, later dismissed

2022-06-08 03:44 UTC, malinthar requested changes

2022-06-08 03:44 UTC, malinthar commented on docs/language-server/README.md
> +3. Best practices to followed when implementing language server features
```suggestion
3. Best practices to be followed when implementing language server features
```

2022-06-10 09:48 UTC, malinthar approved these changes
LGTM!

2022-06-10 09:53 UTC, merged