Added new endpoint to get function definition given position
ballerina-platform/ballerina-lang pull request #36958
Opened 2022-07-12 05:03 UTC by axewilledge

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues.

Fixes # https://github.com/wso2-enterprise/choreo/issues/12425

## Approach
> Describe how you are implementing the solutions along with the design details.
Added new endpoint to fetch definition from given position and function name

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-08-17 14:40 UTC, IMS94 requested changes

2022-08-17 14:40 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentService.java
> +                Optional<Document> srcFile = this.workspaceManagerProxy.get().document(filePath.get());
Is this something going to be called from the expression editor? If that's the case, the file URI will have `expr` scheme. We should use the `workspaceManegerProxy.get(fileUri)` method then.

2022-08-17 14:40 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentService.java
> +                Optional<SemanticModel> semanticModel = this.workspaceManagerProxy.get().semanticModel(filePath.get());
Same as above. Use the `get(fileUri)` method if this is called from the diagram editor/expression editor.

2022-08-17 14:40 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentService.java
> +                Optional<Project> project = this.workspaceManagerProxy.get().project(filePath.get());
Same as above

2022-08-18 11:31 UTC, NipunaRanasinghe approved these changes
LGTM

2022-08-18 14:05 UTC, IMS94 approved these changes

2022-08-18 15:25 UTC, merged