Add change variable type from int to float in modular level
ballerina-platform/ballerina-lang pull request #36987
Opened 2022-07-14 06:14 UTC by bimsarapathiraja

## Purpose
Change variable code action is not available in modular level

Fixes #36682

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-08-03 05:27 UTC, malinthar requested changes

2022-08-03 05:27 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
> +                 BindingPatternNode mBindingPatternNode = mVariableDeclrNode.typedBindingPattern().bindingPattern();
```suggestion
                 BindingPatternNode mBindingPatternNode = ((ModuleVariableDeclarationNode) matchedNode).typedBindingPattern().bindingPattern();
```

2022-08-03 05:27 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
> +                 return Optional.of(mCaptureBindingPatternNode.variableName().text());
```suggestion
                 return Optional.of(((CaptureBindingPatternNode) mBindingPatternNode).variableName().text());
```

2022-08-03 05:27 UTC, malinthar commented on language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/source/changeVarType_int_to_float.bal
> +int x = 10.0;
New line

2022-08-03 05:27 UTC, malinthar commented on language-server/modules/langserver-core/src/test/resources/codeaction/change-var-type/config/changeVarType_int_to_float.json
> + }
Let's add a new line

2022-08-03 05:50 UTC, gayalkuruppu requested changes
Shall we add a test case for constant as well? The test case is mentioned in the original issue.  And we can include a `description` in the config file as well.

2022-08-05 04:40 UTC, malinthar submitted a review, later dismissed
LGTM!

2022-08-22 08:53 UTC, gayalkuruppu approved these changes
LGTM

2022-08-22 09:05 UTC, merged