Fix query functions being invoked as async
ballerina-platform/ballerina-lang pull request #37015
Opened 2022-07-14 18:40 UTC by pcnfernando

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues.

Related to https://github.com/ballerina-platform/module-ballerinai-transaction/issues/408

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-07-20 08:05 UTC, gimantha approved these changes
LGTM

2022-07-22 06:35 UTC, warunalakshitha requested changes

2022-07-22 06:35 UTC, warunalakshitha commented on langlib/lang.__internal/src/main/java/org/ballerinalang/langlib/internal/InvokeAsExternal.java
> +        return AsyncUtils.invokeFunctionPointerAsyncTransactional(function, null, METADATA,
This will break if any other function use function.asyncCall. IMO We need to modify asyncCall to copy the trans action context

2022-07-26 01:16 UTC, warunalakshitha commented on bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/scheduling/Scheduler.java
> -        Strand newStrand = new Strand(name, metadata, this, parent, properties);
Shall we remove this Strand constructor as well. I think that don't have any usages.

2022-07-26 10:16 UTC, warunalakshitha approved these changes

2022-07-26 11:30 UTC, gimantha approved these changes

2022-07-26 11:30 UTC, merged