Fix code actions which are not supported in the code but passes the tests, to work
ballerina-platform/ballerina-lang pull request #37129
Opened 2022-07-26 10:12 UTC by gayalkuruppu

## Purpose
> Some tests are passing in the `AbstractCodeActionTest` but they do not support the code action. With the fix, `AbstractCodeActionTest` is fixed to not pass tests which are not actually passing and fixes the code action logic of `CodeActionNodeValidator`,  `MakeConstructPublicCodeAction`.

Fixes #37128

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-07-26 10:47 UTC, IMS94 requested changes
LGTM! Added a minor suggestion.

2022-07-26 10:47 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/CodeActionNodeValidator.java
> +                ? node.parent().apply(this) : true;
We can rewrite this as:
```
&& node.parent() != null && (node.parent().kind() == SyntaxKind.TYPED_BINDING_PATTERN || node.parent().apply(this));
```

2022-07-26 11:52 UTC, IMS94 approved these changes

2022-07-27 03:09 UTC, TharushiJay approved these changes
LGTM

2022-07-27 05:16 UTC, IMS94 approved these changes

2022-07-27 05:19 UTC, merged