Improve import module code action and create variable code action
ballerina-platform/ballerina-lang pull request #37170
Opened 2022-07-28 20:21 UTC by IMS94

## Purpose
$subject

Fixes #36745
Fixes #36633

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-07-29 08:58 UTC, mindula commented on language-server/modules/langserver-core/src/test/resources/codeaction/import-module/source/project/main.bal
> +}
Shall we add a new line here?

2022-08-01 01:43 UTC, malinthar requested changes

2022-08-01 01:43 UTC, malinthar commented on language-server/modules/langserver-core/src/test/resources/codeaction/import-module/source/project/Ballerina.toml
> +[build-options]
Shall we exclude this build option. This might cause compilation errors as we don't have the `observability pack`  in the lang

2022-08-08 10:41 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/changetype/ChangeVariableTypeCodeAction.java
> +        if (typeSymbol.typeKind() == TypeDescKind.COMPILATION_ERROR || typeSymbol.typeKind() == TypeDescKind.NONE) {
Here we are taking the type from the diagnostic. I couldn't think of a scenario where we can get stream/tuple, etc as type. Can you think of one?

2022-08-10 11:11 UTC, malinthar approved these changes
LGTM!

2022-08-12 03:50 UTC, merged