Create function code action for lhs conditionals
ballerina-platform/ballerina-lang pull request #37197
Opened 2022-08-02 05:33 UTC by bimsarapathiraja

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues.

Fixes #36321

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-08-03 04:06 UTC, malinthar requested changes
Changes look good! Let's address the following minor comments.

2022-08-03 04:06 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/visitors/FunctionCallExpressionTypeFinder.java
> +                conditionalExpressionNode.lhsExpression().lineRange())) {
Let's add the `!conditionalExpressionNode.lhsExpression().isMissing()` condition as well

2022-08-03 04:06 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/command/visitors/FunctionCallExpressionTypeFinder.java
> +            checkAndSetTypeDescResult(TypeDescKind.BOOLEAN);
Now that we have introduced the TypesAPI, we can use `checkAndSetTypeResult(semanticModel.get().types().BOOLEAN)`

2022-08-03 04:06 UTC, malinthar commented on language-server/modules/langserver-core/src/test/resources/command/create-function/config/create_function_in_conditional_expression.json
> +}
Let's add a new line

2022-08-03 04:06 UTC, malinthar commented on language-server/modules/langserver-core/src/test/resources/command/create-function/source/create_function_in_conditional_expression.bal
> +}
new line

2022-08-04 05:49 UTC, mohanvive commented
@bimsarapathiraja Shall we address the review comments and the conflicts.

2022-09-02 02:25 UTC, gayalkuruppu approved these changes
LGTM

2022-09-02 03:11 UTC, mohanvive commented
> Changes look good! Let's address the following minor comments.

@malinthar Need your review and approval to merge this.

2022-09-18 18:46 UTC, mohanvive approved these changes

2022-09-18 18:47 UTC, merged