Added new endpoint to get function definition given position
ballerina-platform/ballerina-lang pull request #37330
Opened 2022-08-10 06:28 UTC by axewilledge

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues.

Fixes # https://github.com/wso2-enterprise/choreo/issues/12425

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-08-12 03:27 UTC, IMS94 requested changes
Can we improve the test coverage of the patch?

2022-08-17 05:41 UTC, NipunaRanasinghe requested changes

2022-08-17 05:41 UTC, NipunaRanasinghe commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentService.java
> +                String functionPath = functionSymbol.get().getLocation().get().lineRange().filePath();
Shall we add a recovery logic(or throw a proper exception) to avoid `NoSuchElementException`s incase the `functionSymbol` is empty?

2022-08-17 05:41 UTC, NipunaRanasinghe commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaSyntaxTreeByNameRequest.java
> + *  Copyright (c) 2021, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```suggestion
 *  Copyright (c) 2022, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```

2022-08-17 05:41 UTC, NipunaRanasinghe commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaSyntaxTreeByNameRequest.java
> + * @since 2.0.0
```suggestion
 * @since 2201.3.0
```

2022-08-17 05:41 UTC, NipunaRanasinghe commented on language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/extensions/document/SyntaxTreeByNameTest.java
> +package org.ballerinalang.langserver.extensions.document;
Missing license header

2022-08-17 05:41 UTC, NipunaRanasinghe commented on language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/extensions/document/SyntaxTreeByNameTest.java
> + * @since 2.0.0
```suggestion
 * @since 2201.3.0
```

2022-08-17 05:41 UTC, NipunaRanasinghe commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/extensions/ballerina/document/BallerinaDocumentService.java
> +            AtomicReference<String> sourceCode = new AtomicReference<>();
IIRC here we won't need to use Atomic References as these are in-scope variables of the `supplyAsync` invocation.

2022-08-17 05:41 UTC, NipunaRanasinghe commented on language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/extensions/LSExtensionTestUtil.java
> +    }
missing newline after the method

2022-08-17 05:41 UTC, NipunaRanasinghe commented on language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/extensions/document/SyntaxTreeByNameTest.java
> +    }
This has the same method name + description compared to the first test case (L42). Is that intentional?

2022-10-08 04:57 UTC, IMS94 commented
@axewilledge Shouldn't this changes go to 2201.2.x, 2201.3.x and master? I see the one for 2201.1.x has been merged.

2022-10-11 06:26 UTC, axewilledge commented
> @axewilledge Shouldn't this changes go to 2201.2.x, 2201.3.x and master? I see the one for 2201.1.x has been merged.

I have added to 2201.2.x one. https://github.com/ballerina-platform/ballerina-lang/pull/36961
but not for 2201.3.x

2022-11-03 07:42 UTC, NipunaRanasinghe approved these changes
LGTM

2022-12-29 08:03 UTC, NipunaRanasinghe approved these changes

2023-01-18 06:21 UTC, IMS94 approved these changes

2023-01-18 06:39 UTC, merged