Add `from` keyword to common query completions
ballerina-platform/ballerina-lang pull request #37485
Opened 2022-08-23 04:27 UTC by LakshanWeerasinghe

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues.

Fixes #37245

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-08-23 05:35 UTC, malinthar requested changes
Changes look good!. However, one thing that we can do is adding few tests to cover the cases where from clause used as a intermediate-clause. 
Note: In the existing test cases we have not covered such cases. Following is one example to start with. Let's try out few scenarios and check if the LS support is desirable in those cases.

Eg:
```Ballerina
import ballerina/io;
public function main() {
    string[] result = from int a in [1,2,3] let int b = a * a 
    from string d in ["one","two","three"] let string power = string `${d}:${b}` select power;
    io:print(result);
}
```

2022-09-08 04:10 UTC, mohanvive approved these changes

2022-09-08 04:10 UTC, mohanvive commented
@malinthar Need to review on this.

2022-09-16 03:55 UTC, malinthar approved these changes
LGTM!

2022-09-19 05:27 UTC, merged