Fix module level completions before and after module level decls and defns
ballerina-platform/ballerina-lang pull request #37658
Opened 2022-09-07 03:11 UTC by gayalkuruppu

## Purpose

1. Fix module level completions before and after module level declarations and definitions
2. Deprioritise completion item `main()` function call in the completion list.
3. Fix completions for qualified name references inside function call expression

Fixes #37444

## Approach

1. Route completions to parent when the cursor position is incorrectly identified as a module level decl/ defn.
2. Make the sort text of function call completion item of `main()` in default sorting
3. Sort qualified name reference completions in function call expression

## Samples

https://user-images.githubusercontent.com/46120162/188779570-add8b571-10b9-4e48-9069-c20b159b2127.mov

## Remarks
1. Future - fix the order to get the service templates after the snippet completion items and give priority to the basic types. Also do not provide `import` keyword after some other module declaration.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-09-08 07:42 UTC, hasithaa commented
What is the new order? 

![image](https://user-images.githubusercontent.com/1356214/189058893-c070ae7c-a438-4e33-b44d-5aa5d140594e.png)

I would suggest sorting it in the following order. Here I have prioritized end users over library developers. 

- main function (hide this if the main function already exits)
- service
- function 
- variable
- configurable
- both open and close record type definition template
- array type definition template. 
- class 
- enum 
- Other top-level constructs.

2022-09-08 07:55 UTC, hasithaa commented
> > What is the new order?
> > ![image](https://user-images.githubusercontent.com/1356214/189058893-c070ae7c-a438-4e33-b44d-5aa5d140594e.png)
> > I would suggest sorting it in the following order. Here I have prioritized end users over library developers.
> > 
> > * main function (hide this if the main function already exits)
> > * service
> > * function
> > * variable
> > * configurable
> > * both open and close record type definition template
> > * array type definition template.
> > * class
> > * enum
> > * Other top-level constructs.
> 
> @hasithaa I have fixed 3 problems mentioned in the Purpose/Approach and created this new issue to fix the order of the completions #37661. Created this issue separately due to the refactoring needed. (BTW, the deprioritization has been done for the `main()` function call but not the `public main function` snippet)

Thanks, will point out my comment in the new issue.

2022-09-20 03:17 UTC, malinthar requested changes
Changes looks good. However, we need to address the following as well. Here, the initializer of the  testClient is not complete. Hence, should we consider this cursor position a part of the initializer. If so, we should not provide completions items like "annotation" , etc snippets. I think it resolves to the module context completion  provider. WDYT @IMS94 @mohanvive @TharushiJay 

![image](https://user-images.githubusercontent.com/35211477/191159681-d1944d52-f8df-47a6-a2bb-c32498d80270.png)

2022-09-20 03:17 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ServiceDeclarationNodeContext.java
> +                && cursor <= node.closeBraceToken().textRange().endOffset();
Let's check if the closeBraceToken is not missing

2022-09-20 03:17 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/TypeDefinitionNodeContext.java
> +                && cursor <= node.semicolonToken().textRange().endOffset();
ditto

2022-09-20 07:22 UTC, gayalkuruppu commented
> Changes looks good. However, we need to address the following as well. Here, the initializer of the testClient is not complete. Hence, should we consider this cursor position a part of the initializer. If so, we should not provide completions items like "annotation" , etc snippets. I think it resolves to the module context completion provider. WDYT @gayalkuruppu @IMS94 @mohanvive
> 
> ![image](https://user-images.githubusercontent.com/35211477/191159681-d1944d52-f8df-47a6-a2bb-c32498d80270.png)

@malinthar  The scope of the issue was to fix completions when a module part declarations are complete. check https://github.com/ballerina-platform/ballerina-lang/issues/37444#issuecomment-1228201961 If we are considering all these scenarios, there are many more cases to fix than this.

2022-09-21 08:54 UTC, gayalkuruppu commented
> Changes looks good. However, we need to address the following as well. Here, the initializer of the testClient is not complete. Hence, should we consider this cursor position a part of the initializer. If so, we should not provide completions items like "annotation" , etc snippets. I think it resolves to the module context completion provider. WDYT @gayalkuruppu @IMS94 @mohanvive
> 
> ![image](https://user-images.githubusercontent.com/35211477/191159681-d1944d52-f8df-47a6-a2bb-c32498d80270.png)

Are you suggesting to route to a child at the completion router? (here this case is identified as ModulePartNode and we only route to the parent in the current completion router implmentation)

2022-09-21 09:12 UTC, gayalkuruppu commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ConstantDeclarationNodeContext.java
> +                && cursor <= node.semicolonToken().textRange().endOffset();
In the ``semicolonToken().isMissing` case, `cursor <= node.semicolonToken().textRange().endOffset()` is always true.

2022-09-27 09:05 UTC, malinthar approved these changes
LGTM!

2022-10-06 04:20 UTC, LakshanWeerasinghe reviewed
We also can add declaration of a `configurable` and  a `template` to the test case.

2022-10-21 09:36 UTC, IMS94 commented
Closing this since there are separate PRs #38241 and #38045 send to master and 2201.3.x

2022-10-21 09:36 UTC, closed without merging