Add code action to generate modules for client declaration
ballerina-platform/ballerina-lang pull request #37743
Opened 2022-09-15 04:52 UTC by malinthar

## Purpose
$subject

Fixes #37682 

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-09-26 12:02 UTC, gayalkuruppu commented
1. Module level completions are not working with this NPE

steps to reproduce: 
```
client "https://postman-echo.com/get?name=projectapiclientplugin" as myapi; 
<cur>
```
```
[Error - 5:20:32 PM] Operation 'textDocument/semanticTokens/full' failed! {uri: '/Users/gayal/Documents/learnBal/client_decl_test/main.bal', error: 'java.lang.NullPointerException'}
java.lang.NullPointerException
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:351)
	at io.ballerina.projects.ModuleContext.resolveDependencies(ModuleContext.java:348)
	at io.ballerina.projects.PackageContext.resolveModuleDependencies(PackageContext.java:317)
	at io.ballerina.projects.PackageContext.resolveDependencies(PackageContext.java:305)
	at io.ballerina.projects.PackageResolution.resolveDependencies(PackageResolution.java:472)
	at io.ballerina.projects.PackageResolution.<init>(PackageResolution.java:111)
	at io.ballerina.projects.PackageResolution.from(PackageResolution.java:116)
	at io.ballerina.projects.PackageContext.getResolution(PackageContext.java:251)
	at io.ballerina.projects.PackageCompilation.<init>(PackageCompilation.java:66)
	at io.ballerina.projects.PackageCompilation.from(PackageCompilation.java:93)
	at io.ballerina.projects.PackageContext.getPackageCompilation(PackageContext.java:223)
	at io.ballerina.projects.Package.getCompilation(Package.java:150)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.waitAndGetPackageCompilation(BallerinaWorkspaceManager.java:272)
	at org.ballerinalang.langserver.workspace.BallerinaWorkspaceManager.semanticModel(BallerinaWorkspaceManager.java:241)
	at org.ballerinalang.langserver.contexts.AbstractDocumentServiceContext.currentSemanticModel(AbstractDocumentServiceContext.java:236)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.handleReferences(SemanticTokensVisitor.java:668)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.addSemanticToken(SemanticTokensVisitor.java:654)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.visit(SemanticTokensVisitor.java:134)
	at io.ballerina.compiler.syntax.tree.FunctionDefinitionNode.accept(FunctionDefinitionNode.java:66)
	at io.ballerina.compiler.syntax.tree.NodeVisitor.visitSyntaxNode(NodeVisitor.java:870)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensVisitor.getSemanticTokens(SemanticTokensVisitor.java:107)
	at org.ballerinalang.langserver.semantictokens.SemanticTokensUtils.getSemanticTokens(SemanticTokensUtils.java:64)
	at org.ballerinalang.langserver.BallerinaTextDocumentService.lambda$semanticTokensFull$16(BallerinaTextDocumentService.java:652)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

2. When the generated client is changed (steps to reproduce: when adding a new remote method), that change is not updated until we do a reload. 

```

2022-09-28 06:10 UTC, LakshanWeerasinghe requested changes

2022-09-28 08:22 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/GenerateModuleForClientDeclCodeAction.java
> +    private static final String NAME = "Generate Module Client Declaration";
Shall we use `GENERATE_MODULE_FOR_CLIENT_DECLARATION` instead? With no spaces in between

2022-09-28 08:43 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/GenerateModuleForClientDeclCodeAction.java
> +    private static final String NAME = "Generate Module Client Declaration";
+1

2022-09-29 04:26 UTC, merged