[2201.2.x] Improve obj field mapping constructor completions
ballerina-platform/ballerina-lang pull request #37742
Opened 2022-09-15 04:22 UTC by LakshanWeerasinghe

## Purpose
$subject

Fixes #37625

Related PRs - #38367 (2201.3.x), #38370 (master)

## Samples
<img width="719" alt="Screenshot 2022-09-15 at 09 49 16" src="https://user-images.githubusercontent.com/46857198/190313611-84449eae-1ca9-4741-94c7-fc7d7de0228b.png">

<img width="802" alt="Screenshot 2022-09-15 at 09 49 51" src="https://user-images.githubusercontent.com/46857198/190313618-2f3e963b-bc31-4962-92b7-bf2301da9763.png">

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-09-15 06:17 UTC, gayalkuruppu reviewed
Changes look good to me. Just a small suggestion to add the description field to the config files.

2022-09-15 06:17 UTC, gayalkuruppu commented on language-server/modules/langserver-core/src/test/resources/completion/expression_context/config/mapping_constructor_expr_ctx_config1.json
> +  "source": "expression_context/source/mapping_constructor_expr_ctx_source1.bal",
Shall we add a description here?

2022-09-16 05:32 UTC, gayalkuruppu submitted a review, later dismissed
LGTM

2022-09-20 01:36 UTC, malinthar requested changes
Shall we address the following cases as well. 

1. Suggest variable names(object field names) in mapping constructor
```Ballerina
int moduleVar = 20;

class MyClass {
    int x = 10;
    int y = 20;
    record {int y; int x;} rec = {x, <cursor>};
}
```
Here we should get a completion item for `y`(object fields) as we have done other variables.
![image](https://user-images.githubusercontent.com/35211477/191147755-19dd3935-9f5d-4a49-9530-4f2b4ac1e777.png)




```
2. Provide object fields for the value expression
![image](https://user-images.githubusercontent.com/35211477/191147900-870b450b-1d50-4cf5-a2a3-612eca0a2b43.png)

we should include `x` and `y` in the completion item list

2022-09-23 05:45 UTC, LakshanWeerasinghe commented
> Shall we address the following cases as well.
> 
> 1. Suggest variable names(object field names) in mapping constructor
> 
> ```ballerina
> int moduleVar = 20;
> 
> class MyClass {
>     int x = 10;
>     int y = 20;
>     record {int y; int x;} rec = {x, <cursor>};
> }
> ```
> 
> Here we should get a completion item for `y`(object fields) as we have done other variables. ![image](https://user-images.githubusercontent.com/35211477/191147755-19dd3935-9f5d-4a49-9530-4f2b4ac1e777.png)
> 
> 2. Provide object fields for the value expression
>    ![image](https://user-images.githubusercontent.com/35211477/191147900-870b450b-1d50-4cf5-a2a3-612eca0a2b43.png)
> 
> we should include `x` and `y` in the completion item list

I have add these two scenarios.

2022-10-25 03:59 UTC, LakshanWeerasinghe commented
Closing this PR in favor of #38367 (2201.3.x) and #38370 (master).

2022-10-25 03:59 UTC, closed without merging