Add Type compltion items to named arg context
ballerina-platform/ballerina-lang pull request #38204
Opened 2022-10-14 04:29 UTC by malinthar

## Purpose
$subject

Fixes #37562

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-10-26 06:47 UTC, mindula commented on language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/completion/CompletionTest.java
> +            updateConfig(configJsonPath, testConfig, responseItemList);
let's comment out this line

2022-10-27 05:37 UTC, IMS94 requested changes
LGTM! Added minor suggestion. And please address Mindula's comment

2022-10-27 05:37 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/util/ContextTypeResolver.java
> +                            .map(name -> name.equals(namedArgumentNode.argumentName().name().text())).orElse(false)) {
We can rewrite this as:
```
if (parameterSymbol.getName()
                            .filter(name -> name.equals(namedArgumentNode.argumentName().name().text()))
                            .isPresent()) {
```

2022-11-08 08:13 UTC, mohanvive approved these changes

2022-11-08 08:13 UTC, merged