Add type infer methods to language server stdlib module
ballerina-platform/ballerina-lang pull request #38212
Opened 2022-10-14 10:49 UTC by LakshanWeerasinghe

## Purpose
Type infer methods are required to test some features provide by the language server. This pr will add four type infer methods to the `client_source.bal` inside the language server stdlib module.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-10-14 16:21 UTC, malinthar requested changes
Let's fix the failing LS test cases. The failures are  probably due to new symbols that we have added!

2022-10-14 16:21 UTC, malinthar commented on language-server/modules/langserver-stdlib/src/main/java/org/ballerinalang/langserver/stdlib/ClientAction.java
> + * @since 2201.3.0
Let's change version to 2201.4.0 since we are sending this to the master branch

2022-10-18 03:28 UTC, IMS94 approved these changes

2022-10-18 03:38 UTC, malinthar approved these changes

2022-10-18 03:44 UTC, merged