Fix completions when invoking remote methods for records
ballerina-platform/ballerina-lang pull request #38229
Opened 2022-10-17 06:40 UTC by gayalkuruppu

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues.

Fixes #38038

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-10-19 04:17 UTC, LakshanWeerasinghe requested changes

2022-10-19 04:17 UTC, LakshanWeerasinghe commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/builder/NamedArgCompletionItemBuilder.java
> +        String defaultValueTooDetail = DefaultValueGenerationUtil.getDefaultValueForType(argSymbol).orElse("");
```suggestion
        String defaultValueToDetail = DefaultValueGenerationUtil.getDefaultValueForType(argSymbol).orElse("");
```

2022-10-21 05:58 UTC, malinthar approved these changes
LGTM!

2022-10-21 06:59 UTC, LakshanWeerasinghe approved these changes
LGTM

2022-10-21 09:06 UTC, merged