Update LS simulator workflow
ballerina-platform/ballerina-lang pull request #38230
Opened 2022-10-17 06:50 UTC by gayalkuruppu

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues.

Fixes #<Issue Number>

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-10-18 01:41 UTC, malinthar requested changes

2022-10-18 01:41 UTC, malinthar commented on .github/workflows/language_server_simulator.yml
> +        branch: ["master", "2201.0.x", "2201.2.x", "2201.2.0-stage", "2201.3.x", "2201.3.0-stage"]
```suggestion
        branch: ["master", "2201.2.x", "2201.2.2-stage", "2201.3.x", "2201.3.0-stage"]
```

2022-10-18 03:19 UTC, IMS94 commented on .github/workflows/language_server_simulator.yml
> +        branch: ["master", "2201.0.x", "2201.2.x", "2201.2.0-stage", "2201.3.x", "2201.3.0-stage"]
We should keep `2201.1.x` as well.

2022-10-18 03:59 UTC, IMS94 requested changes

2022-10-18 03:59 UTC, IMS94 commented on .github/workflows/language_server_simulator.yml
> +        branch: ["master", "2201.0.x", "2201.1.x", "2201.2.x", "2201.2.2-stage", "2201.3.x", "2201.3.0-stage"]
```suggestion
        branch: ["master", "2201.1.x", "2201.2.x", "2201.2.2-stage", "2201.3.x", "2201.3.0-stage"]
```
We can remove 2201.0.x branch

2022-10-18 04:04 UTC, IMS94 approved these changes

2022-10-21 05:32 UTC, IMS94 approved these changes

2022-10-21 05:32 UTC, merged