[master] Improve obj field mapping constructor completions
ballerina-platform/ballerina-lang pull request #38370
Opened 2022-10-25 03:56 UTC by LakshanWeerasinghe

## Purpose
$subject

Fixes #37625

Related PRs - #37742(2201.2.x), #38367(2201.3.x)

## Samples
<img width="719" alt="Screenshot 2022-09-15 at 09 49 16" src="https://user-images.githubusercontent.com/46857198/190313611-84449eae-1ca9-4741-94c7-fc7d7de0228b.png">

<img width="802" alt="Screenshot 2022-09-15 at 09 49 51" src="https://user-images.githubusercontent.com/46857198/190313618-2f3e963b-bc31-4962-92b7-bf2301da9763.png">

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-10-26 00:44 UTC, malinthar submitted a review, later dismissed
LGTM!

2022-10-26 03:14 UTC, IMS94 requested changes

2022-10-26 03:14 UTC, IMS94 commented on language-server/modules/langserver-core/src/test/resources/completion/expression_context/source/mapping_constructor_expr_ctx_source4.bal
> +    record {int y; int x;} rec = {x, };
Shall we add another test case here with the record being defined as a type:
```
type Employee record {|
    readonly int empId;
    string name;
|}; 
```
And inside the class:
```
Employee emp = {x, };
```

2022-11-02 07:29 UTC, IMS94 approved these changes

2022-11-02 07:30 UTC, merged