Improve sorting in module part context
ballerina-platform/ballerina-lang pull request #38447
Opened 2022-10-28 10:19 UTC by malinthar

## Purpose
$subject

Fixes #37661

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-11-11 12:08 UTC, TharushiJay commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java
>  import javax.annotation.Nonnull;
Checkstyle failure `'javax.annotation.Nonnull' should be separated from previous imports.`

2022-11-23 20:03 UTC, IMS94 requested changes

2022-11-23 20:03 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/AbstractCompletionProvider.java
> +    protected List<LSCompletionItem> getInBuildTypes(BallerinaCompletionContext context) {
Method name should be `getInBuiltTypes()`

2022-11-23 21:32 UTC, gayalkuruppu reviewed
1. Is there a specific reason to include `service` keyword after the service snippets but not `function` keyword after function snippet?
2. Is there a way that we can improve following scenarios(only those of which are within the scope of this PR/issue)
 a. getting `main function` snippet in `test.bal`
 b. not getting relevant completions after `public` (here we get `error` after `public`)
 c. getting `main function` snippet after `public`

https://user-images.githubusercontent.com/46120162/203648932-ad9e423d-6888-4702-96c3-4026080ee858.mov

2022-11-24 06:33 UTC, IMS94 requested changes

2022-11-24 06:33 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/util/ModulePartNodeContextUtil.java
> +        return modulePartNode.get().members().stream().anyMatch(moduleMemberDeclarationNode ->
I think we should be able to use `visibleSymbols` to determine if we have a `main()` function already. Shall we use that approach?

2022-11-24 09:23 UTC, gayalkuruppu commented
> 

Created https://github.com/ballerina-platform/ballerina-lang/issues/38817 to track 2.a and 2.b

2022-11-24 10:15 UTC, gayalkuruppu commented
Previously I had a hard time getting the `string` completion item which is used more often than `stream`, and it was annoying as a user(hope this is relatable to others as well).

<img width="721" alt="Screenshot 2022-11-24 at 15 38 17" src="https://user-images.githubusercontent.com/46120162/203757260-b828c327-56dc-4acd-a060-a26c65ceeb83.png">

But with this new refactoring we get the `string` completion item before `stream` and it so satisfying. 

<img width="733" alt="Screenshot 2022-11-24 at 15 38 31" src="https://user-images.githubusercontent.com/46120162/203757437-f8a80524-66b4-4cb0-a004-c763ba93b411.png">

Maybe we can use this as an example to improve UX in future. It can be a whole new different scenario, but can make a huge difference for a regular user.

2022-12-01 18:33 UTC, malinthar commented
> 1. Is there a specific reason to include `service` keyword after the service snippets but not `function` keyword after function snippet?
> 
>     2. Is there a way that we can improve following scenarios(only those of which are within the scope of this PR/issue)
>        a. getting `main function` snippet in `test.bal`
>        b. not getting relevant completions after `public` (here we get `error` after `public`)
>        c. getting `main function` snippet after `public`
> 
> 
> Screen.Recording.2022-11-24.at.02.51.53.mov

service is a module level member in ballerina. That's why we have special cased it. We can special case the function keyword as well. +1

2022-12-02 06:32 UTC, IMS94 commented
Shall we send this to 2201.3.x as well?

2022-12-15 11:31 UTC, IMS94 approved these changes

2022-12-15 11:31 UTC, merged