Update LSP4J version to 0.15.0
ballerina-platform/ballerina-lang pull request #38633
Opened 2022-11-11 07:58 UTC by mindula

## Purpose
This PR updates the LSP4J version of language server to 0.15.0

Fixes #38108

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-11-14 06:00 UTC, malinthar requested changes
Let's link the related PR for vscode-plugin repo as well

2022-11-17 03:06 UTC, malinthar submitted a review, later dismissed
LGTM!

2023-02-15 16:04 UTC, IMS94 submitted a review, later dismissed

2023-02-20 08:09 UTC, malinthar requested changes

2023-02-20 08:09 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaNotebookDocumentService.java
> + * Copyright (c) 2022, WSO2 LLC. (http://wso2.com) All Rights Reserved.
```suggestion
 * Copyright (c) 2023, WSO2 LLC. (http://wso2.com) All Rights Reserved.
```

2023-02-20 13:48 UTC, malinthar approved these changes
LGTM!

2023-02-20 14:24 UTC, IMS94 approved these changes

2023-02-22 06:19 UTC, merged