Add rename popup for extract constant and extract to local variable code actions
ballerina-platform/ballerina-lang pull request #38663
Opened 2022-11-14 17:45 UTC by LakshanWeerasinghe

## Purpose
The purpose of this PR is to add rename popup for extract to constant and extract to local variable code actions.

Fixes #37479

## Approach
In the create variable code action we have already provided rename popup using the rename support capability. In that case we used the character based position details to determine the start position of the newly created variable. (#37135)

With this approach one limitation was when test this on a windows environment, it gives different position due to the windows detect new lines using `\r\n`.  Where on a linux environment it is represent with `\n`. 

In order to overcome this issue we are using a new capability named positional rename support to provide the rename popup for create variable code action, extract to constant code action and extract to local variable code action. With this approach we are using line and character based position details.

When the plugin have both the capabilities the language server will prioritise giving the position details using line and character.

## Samples
https://user-images.githubusercontent.com/46857198/201729338-08c8e240-2ae9-4677-af8e-2aa3d6f31e78.mov

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-11-17 04:28 UTC, TharushiJay commented on language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/capability/InitializationOptions.java
> +    boolean isPositionalRefactoredRenameSupported();
```suggestion
    boolean isPositionalRefactorRenameSupported();
```

2022-11-17 04:28 UTC, TharushiJay commented on language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableWithPositionalRenameSupportCapabilityTest.java
> + *  Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```suggestion
 *  Copyright (c) 2022, WSO2 LLC. (http://www.wso2.org) All Rights Reserved.
```

2022-11-17 04:28 UTC, TharushiJay commented on language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableWithPositionalRenameSupportCapabilityTest.java
> + * Test Cases for CodeActions.
Let's make this description more specific

2022-11-17 04:28 UTC, TharushiJay commented on language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableWithPositionalRenameSupportCapabilityTest.java
> +                .resolve("config-ren-pos-cap")
Shall we avoid using shorthands like this? It's a little difficult to make sense of what it means, at first sight. Let's use something like `config-rename-positional`/`config-rename-positional-capability` instead.

2022-11-17 05:49 UTC, mindula commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/common/ImportsAcceptor.java
> +        String editText = String.format("import %s;%n", pkgName);
Shall we use `ItemResolverConstants.IMPORT`?

2022-11-17 05:50 UTC, mindula commented on language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/AbstractCodeActionTest.java
> +        if ("ballerina.action.positional.rename".equals(actualCommand.get("command").getAsString())) {
Let's move `ballerina.action.positional.rename` to a constant

2022-11-17 05:51 UTC, mindula commented on language-server/modules/langserver-core/src/test/java/org/ballerinalang/langserver/codeaction/CreateVariableTest.java
> +        if ("ballerina.action.rename".equals(actualCommand.get("command").getAsString())) {
Lets use a constant for `ballerina.action.rename`

2023-01-11 06:34 UTC, malinthar requested changes

2023-01-11 06:34 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToConstantCodeAction.java
> +        int line = replacePosition.getLine() + 1;
Can you add a comment explaining why we have to add +1 to the line here

2023-01-11 06:34 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToLocalVarCodeAction.java
> +                    List.of(context.fileUri(), new Position(position.getLine() + 1, position.getCharacter()))));
ditto

2023-01-11 09:23 UTC, malinthar commented
Getting the `element can't be renamed`  message for the following scenario. The rename position may be wrong in this case.
![rename_pop_up](https://user-images.githubusercontent.com/35211477/211767746-8bbc3fef-ca8d-487f-b3bf-f25fcbb06d5e.gif)

2023-01-11 09:25 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToConstantCodeAction.java
> +    private void addRenamePopup(CodeActionContext context, CodeAction codeAction, Position replacePosition,
Shall we make this method a util method as this is used in multiple code actions

2023-01-11 10:03 UTC, LakshanWeerasinghe commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/ExtractToConstantCodeAction.java
> +        if (nodeList.size() == 1) {
We cannot move. If we are moving the condition we have to move this `List<Node> nodeList = getPossibleExpressionNodes(node, nodeValidator);` statement asswell.

2023-01-11 11:36 UTC, LakshanWeerasinghe commented
> Getting the `element can't be renamed` message for the following scenario. The rename position may be wrong in this case. ![rename_pop_up](https://user-images.githubusercontent.com/35211477/211767746-8bbc3fef-ca8d-487f-b3bf-f25fcbb06d5e.gif) [ ![rename_pop_up](https://user-images.githubusercontent.com/35211477/211767746-8bbc3fef-ca8d-487f-b3bf-f25fcbb06d5e.gif) ](https://user-images.githubusercontent.com/35211477/211767746-8bbc3fef-ca8d-487f-b3bf-f25fcbb06d5e.gif) [ ](https://user-images.githubusercontent.com/35211477/211767746-8bbc3fef-ca8d-487f-b3bf-f25fcbb06d5e.gif)

Fixed this. Please use the updated PR for plugin as well.

2023-01-17 15:30 UTC, IMS94 approved these changes

2023-01-18 06:19 UTC, malinthar approved these changes
LGTM!

2023-01-18 09:17 UTC, merged