Stop sending diagnostics when LS in lightweight mode
ballerina-platform/ballerina-lang pull request #38687
Opened 2022-11-16 06:50 UTC by LakshanWeerasinghe

## Purpose
Currently we are not checking weather the LS is in lightweight mode when we are publishing diagnostics. Ballerina compiler toolkit connects to a lightweight language server and it will publish diagnostic messages. Because of this when a user have both plugin and compiler toolkit it shows same diagnostic twice.  

With this PR this incorrect behavior is go away.

Fixes #38431

## Samples
-  how it looks like before the fix.
<img width="587" alt="Screenshot 2022-11-16 at 12 12 16" src="https://user-images.githubusercontent.com/46857198/202105843-fec5e6f9-22e1-43f8-a707-2285416e72d0.png">

- how it looks like after the fix.
<img width="533" alt="Screenshot 2022-11-16 at 12 10 36" src="https://user-images.githubusercontent.com/46857198/202105950-191454c4-2bd7-43d8-938f-6ea0e00140f4.png">

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-11-17 02:15 UTC, malinthar requested changes

2022-11-17 02:15 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/diagnostic/DiagnosticsHelper.java
> +        if (context.languageServercontext().get(LanguageServerLightWeightMode.class) != null) {
Let's add this check to the PublishDiagnoticSubscriber instead https://github.com/ballerina-platform/ballerina-lang/blob/8ccdc067648a303b81e43aa4c67d9a2e96bcfcae/language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/eventsync/subscribers/PublishDiagnosticSubscriber.java#L45

2022-11-17 08:26 UTC, IMS94 requested changes

2022-11-17 08:26 UTC, IMS94 commented on language-server/modules/langserver-commons/src/main/java/org/ballerinalang/langserver/commons/LanguageServerLightWeightMode.java
> +public class LanguageServerLightWeightMode {
We don't need a new class like this. The `InitializeParams` already has a parameter called `enableLightWeightMode`. See `org.ballerinalang.langserver.BallerinaLanguageServer#isLightWeightMode()` method for an example usage. However, we have a better approach.

At `BallerinaLanguageServer:88`, we create an instance of `LSClientCapabilitiesImpl` containing an instance of `InitializationOptions`. We should add the light weight mode boolean as a new method to that interface. And in the other places, use that to determine if we are in lightweight mode.

2022-11-23 06:09 UTC, malinthar approved these changes
LGTM!

2022-11-23 07:20 UTC, IMS94 requested changes

2022-11-23 07:20 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
> +    private LSClientCapabilities capabilities;
This is incorrect. We hold everything inside the `LanguageServerContext`. No need to keep anything at instance level unless necessary. We can simply to ` LSClientCapabilities clientCapabilities = serverContext.get(LSClientCapabilities.class);` to get the client capabilities from LS context.

2022-11-23 07:20 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
> +        Map initializationOptions = null;
We can move the following lines before this line:
```java
        TextDocumentClientCapabilities textDocClientCapabilities = params.getCapabilities().getTextDocument();
        WorkspaceClientCapabilities workspaceClientCapabilities = params.getCapabilities().getWorkspace();
        LSClientCapabilities capabilities = new LSClientCapabilitiesImpl(textDocClientCapabilities,
                workspaceClientCapabilities,
                experimentalClientCapabilities,
                initializationOptions);
        this.serverContext.put(LSClientCapabilities.class, capabilities);
```

And then check 
```
    if (capabilities.getInitializationOptions().isLisghtWeightMode()) {
            return CompletableFuture.supplyAsync(() -> res);
    }
```
And we can remove the `isLightWeightMode()` method as well

2022-11-23 07:20 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/LSClientCapabilitiesImpl.java
> +
Remove this additional new line to match the way other fields are defined.

2022-11-23 07:20 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/eventsync/subscribers/PublishDiagnosticSubscriber.java
> +        if (!lsClientCapabilities.getInitializationOptions().isEnableLSLightWeightMode()) {
There's another place where we publish diagnostics, `BallerinaWorkspaceService.didChangeWatchedFiles()` method. Need to add this check there as well.

2022-11-24 09:35 UTC, IMS94 requested changes

2022-11-24 09:35 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
>      private Boolean isLightWeightMode(InitializeParams params) {
We can remove this method now

2022-11-24 09:35 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/BallerinaLanguageServer.java
> +    private LSClientCapabilities capabilities;
Can you remove this?

2022-11-25 02:18 UTC, IMS94 submitted a review, later dismissed

2022-11-25 02:23 UTC, IMS94 approved these changes

2022-11-25 05:02 UTC, merged