[2201.3.x] Add examples for map langlib
ballerina-platform/ballerina-lang pull request #39076
Opened 2022-12-15 11:44 UTC by dulajdilshan

## Purpose
$title

Fixes #38909 

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2022-12-16 03:22 UTC, SasinduDilshara submitted a review, later dismissed

2022-12-19 05:03 UTC, dulajdilshan commented on langlib/lang.map/src/main/ballerina/map.bal
> +# ```
We don't use ballerina anymore right?

2022-12-19 08:38 UTC, pcnfernando commented on langlib/lang.map/src/main/ballerina/map.bal
> +# marks.filter((m) => m >= 60) ⇒ {"Carl": 85, "Max": 60}
```suggestion
# marks.filter(m => m >= 60) ⇒ {"Carl": 85, "Max": 60}
```

2022-12-19 08:40 UTC, pcnfernando commented on langlib/lang.map/src/main/ballerina/map.bal
> +# marks.reduce(isolated function (int accTot, int next) returns int => accTot + next, 0) ⇒ 195;
As discussed in https://github.com/ballerina-platform/ballerina-lang/pull/39073/files#r1051801231

2022-12-19 08:41 UTC, pcnfernando commented on langlib/lang.map/src/main/ballerina/map.bal
> +# ```
Panic case?

2022-12-19 08:42 UTC, pcnfernando commented on langlib/lang.map/src/main/ballerina/map.bal
> +# marks ⇒ {"Bob": 50, "Max": 60}
Panic case?

2022-12-19 08:43 UTC, pcnfernando commented on langlib/lang.map/src/main/ballerina/map.bal
> +# marks ⇒ {"Bob": 50, "Max": 60}
() return case?

2022-12-19 08:48 UTC, pcnfernando commented on langlib/lang.map/src/main/ballerina/map.bal
> +# marks ⇒ {}
Panic case?

2022-12-19 08:51 UTC, pcnfernando commented on langlib/lang.map/src/main/ballerina/map.bal
> +# ```
Update in all places

2022-12-19 08:51 UTC, pcnfernando commented
@dulajdilshan please check on the build

2022-12-20 17:29 UTC, MaryamZi approved these changes

2022-12-21 05:06 UTC, MaryamZi requested changes

2022-12-21 05:06 UTC, MaryamZi commented on langlib/lang.map/src/main/ballerina/map.bal
> +# makrs.get("John") ⇒ panic
```suggestion
# marks.get("John") ⇒ panic
```

2022-12-21 06:38 UTC, MaryamZi commented on langlib/lang.map/src/main/ballerina/map.bal
> +# } iterator = marks.iterator();
```suggestion
# object {
#     public isolated function next() returns record {|int value;|}?;
# } iterator = {"Carl": 85, "Bob": 50, "Max": 60}.iterator();
```

2022-12-21 06:38 UTC, MaryamZi approved these changes

2022-12-21 06:50 UTC, pcnfernando approved these changes

2022-12-22 03:09 UTC, merged