Improve CreateVariableWithTypeCodeAction, TypeCastCodeAction and resource function snippet
ballerina-platform/ballerina-lang pull request #39304
Opened 2023-01-19 08:50 UTC by IMS94

## Purpose
$subject

Fixes #39160
Fixes #39254
Fixes #39165

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2023-01-24 07:48 UTC, malinthar requested changes

2023-01-24 07:48 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableWithTypeCodeAction.java
> +                || actionNode.get().parent().kind() == SyntaxKind.CHECK_ACTION) {
Duplicated check

2023-01-25 04:50 UTC, IMS94 commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/createvar/CreateVariableWithTypeCodeAction.java
> +                || actionNode.get().parent().kind() == SyntaxKind.CHECK_ACTION) {
Addressed

2023-01-25 05:59 UTC, malinthar submitted a review, later dismissed

2023-01-26 03:17 UTC, malinthar approved these changes

2023-01-26 03:21 UTC, merged