Fix giving field access completions for regexp langlib
ballerina-platform/ballerina-lang pull request #39362
Opened 2023-01-25 07:17 UTC by LakshanWeerasinghe

## Purpose
$subject

Fixes #39336, #39289, #39183 

## Samples
<img width="689" alt="Screenshot 2023-01-25 at 12 42 11" src="https://user-images.githubusercontent.com/46857198/214502648-9c6b3c27-d883-46d2-8fc1-c25111a5730a.png">

<img width="688" alt="Screenshot 2023-01-25 at 12 42 23" src="https://user-images.githubusercontent.com/46857198/214502662-2e1614d1-4e39-492c-9cbb-c028efcdc46f.png">

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [x] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2023-01-25 08:30 UTC, LakshanWeerasinghe commented on language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_ctx_source55.bal
> +    string:RegExp reg = re ``;
I'll add.

2023-01-30 06:03 UTC, malinthar requested changes
@LakshanWeerasinghe https://github.com/ballerina-platform/ballerina-lang/issues/39292 shall we verify that this issue is fixed as well? This happens as the  `Span` type is an intersection with `readonly` type

2023-01-30 06:29 UTC, pcnfernando commented on language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_ctx_source55.bal
> +    string:RegExp reg = re ``;
Seems the prev `string:RegExp` is removed now. My suggestion was to add more keeping the existing one

2023-01-30 06:31 UTC, pcnfernando commented
> @LakshanWeerasinghe #39292 shall we verify that this issue is fixed as well? This happens as the `Span` type is an intersection with `readonly` type

Seems to be a generic issue. Added a comment https://github.com/ballerina-platform/ballerina-lang/issues/39292#issuecomment-1408063830

2023-01-30 07:00 UTC, LakshanWeerasinghe commented
> > @LakshanWeerasinghe #39292 shall we verify that this issue is fixed as well? This happens as the `Span` type is an intersection with `readonly` type
> 
> Seems to be a generic issue. Added a comment [#39292 (comment)](https://github.com/ballerina-platform/ballerina-lang/issues/39292#issuecomment-1408063830)

Since this a generic issue this will be fixed using a separate PR. It will be tracked in #39292.

2023-01-30 07:20 UTC, malinthar submitted a review, later dismissed

2023-01-30 08:01 UTC, LakshanWeerasinghe commented on language-server/modules/langserver-core/src/test/resources/completion/field_access_expression_context/source/field_access_ctx_source55.bal
> +    string:RegExp reg = re ``;
I will add.

2023-01-31 04:25 UTC, pcnfernando approved these changes

2023-01-31 04:51 UTC, IMS94 approved these changes

2023-01-31 04:58 UTC, merged