Replace CodeActionContextTypeResolver with expectedType API
ballerina-platform/ballerina-lang pull request #39811
Opened 2023-03-07 06:28 UTC by mindula

## Purpose
This PR replaces the usages of codeActionContextTypeResolver with the new expectedType API.

Fixes #39108 
Fixes #39225

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2023-03-10 10:51 UTC, IMS94 submitted a review, later dismissed
LGTM!

2023-03-20 07:15 UTC, IMS94 submitted a review, later dismissed

2023-03-20 11:06 UTC, malinthar requested changes

2023-03-20 11:06 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/codeaction/providers/FillRecordFieldsCodeAction.java
> +        Optional<TypeSymbol> typeSymbol = Optional.empty();
you don't have to initialize the typeSymbol to Optional.empty. Alternatively, we can move the logic inside the if condition 94 to the initializer,  by doing an early return if `context.currentSemanticModel().isEmpty()  || context.currentDocument().isEmpty()`.

2023-03-20 12:54 UTC, IMS94 approved these changes

2023-03-21 07:01 UTC, malinthar approved these changes
LGTM!

2023-03-21 07:03 UTC, merged