Fix errors with non-capturing group runtime parsing
ballerina-platform/ballerina-lang pull request #39878
Opened 2023-03-15 03:22 UTC by LakshanWeerasinghe

## Purpose
$subject

Fixes #39769 
Fixes #39768 
Fixes #39767

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2023-03-15 05:19 UTC, SasinduDilshara requested changes

2023-03-15 05:19 UTC, SasinduDilshara commented on bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java
> +
Please refer to https://github.com/ballerina-platform/ballerina-lang/pull/39727#discussion_r1134956518

2023-03-15 05:26 UTC, SasinduDilshara requested changes

2023-03-15 05:26 UTC, SasinduDilshara commented on bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java
> +                break;
We don't need a break statement in here, since it is the last check in the switch case.

2023-03-15 05:26 UTC, SasinduDilshara commented on langlib/langlib-test/src/test/resources/test-src/regexp_negative_test.bal
> +}
Need a new line in here

2023-03-15 05:26 UTC, SasinduDilshara commented on langlib/langlib-test/src/test/resources/test-src/regexp_negative_test.bal
> +}
Shall we add two more tests with only `FlagOn` and only `FlagOff`.
ex:- 
```
* (?imi:(ABC))
* (?-imi:(ABC))
```

2023-03-16 08:54 UTC, SasinduDilshara commented on langlib/langlib-test/src/test/resources/test-src/regexp_negative_test.bal
> +    check assertEqualMessage(result, "Invalid insertion in regular expression: invalid flag in regular expression");
Small suggestion: Shall we add a one test that include both errors.
anydata|error result = trap re `${"(?ii-mk:ABC))"}`;

2023-03-16 08:56 UTC, SasinduDilshara commented on bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeTraverser.java
> -     *    | ControlEscape
This formatting changes are initiated by IntelliJ setting in the local machine.
Imo, We need to remove these

2023-03-16 17:55 UTC, pcnfernando commented on bvm/ballerina-runtime/src/main/java/io/ballerina/runtime/internal/regexp/TreeBuilder.java
> +
Revert these formatings

2023-03-17 15:34 UTC, mohanvive approved these changes

2023-03-18 05:37 UTC, pcnfernando approved these changes

2023-03-18 05:41 UTC, SasinduDilshara approved these changes

2023-03-18 05:43 UTC, merged