Fix Query Actions in Ballerina Shell
ballerina-platform/ballerina-lang pull request #39887
Opened 2023-03-15 08:05 UTC by DamithaSenevirathne

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues.

Fixes #34824

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2023-03-18 16:32 UTC, sanjana commented on ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/snippet/factory/BasicSnippetFactory.java
> +
```suggestion
```

2023-03-18 16:32 UTC, sanjana commented on ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/snippet/factory/BasicSnippetFactory.java
> +
```suggestion
```

2023-03-18 16:36 UTC, sanjana requested changes
Minor formatting suggestions.

2023-04-21 03:23 UTC, sanjana commented on ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/snippet/factory/SnippetFactory.java
> +     * Creates a snippets from the given node.
```suggestion
     * Creates snippets from the given node.
```

2023-04-21 03:24 UTC, sanjana commented on ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/snippet/factory/SnippetFactory.java
> +     * Creates a snippets from the given node.
```suggestion
     * Creates snippets from the given node.
```

Ditto

2023-04-21 03:24 UTC, sanjana commented on ballerina-shell/modules/shell-core/src/main/java/io/ballerina/shell/snippet/factory/SnippetFactory.java
> +     * Create a variable declaration snippets from the given node.
```suggestion
     * Create variable declaration snippets from the given node.
```

Ditto.

2023-04-21 03:24 UTC, sanjana submitted a review, later dismissed
Simple grammatical errors.

2023-06-09 08:38 UTC, hasithaa approved these changes

2023-06-09 08:38 UTC, merged