Add semanticAPI support for collect clause
ballerina-platform/ballerina-lang pull request #40433
Opened 2023-05-17 06:24 UTC by TharushiJay

## Purpose
$subject

Fixes https://github.com/ballerina-platform/ballerina-lang/issues/40432

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2023-05-17 10:57 UTC, gimantha approved these changes

2023-05-17 10:59 UTC, rdulmina commented on compiler/ballerina-lang/src/main/java/io/ballerina/compiler/api/impl/EnvironmentResolver.java
> +            return;
R these codecov hits false positives?

2023-05-17 11:10 UTC, dulajdilshan requested changes
Shall we add Semantic API tests covering the SymbolFinder, ReferenceFinder, NodeFinder, and EnvironmentResolver changes?

Ex: symbol(), references(), etc

2023-05-18 04:18 UTC, TharushiJay commented
> Other changes are okay. Shall we add Semantic API tests?
> 
> Ex: symbol(), references(), etc. what ever applicable

Will be addressed with https://github.com/ballerina-platform/ballerina-lang/issues/40449

2023-05-18 04:27 UTC, dulajdilshan approved these changes

2023-05-18 04:47 UTC, merged