[Query Expression]Restrict result type being resolved as `map` without the query-construct-type
ballerina-platform/ballerina-lang pull request #41117
Opened 2023-07-28 14:27 UTC by pcnfernando

## Purpose
> Describe the problems, issues, or needs driving this feature/fix and include links to related issues.

Fixes #37450
Fixes #37670
Fixes #41129
Fixes #37256

## Approach
> Describe how you are implementing the solutions along with the design details.

## Samples
> Provide high-level details about the samples related to this feature.

## Remarks
> List any other known issues, related PRs, TODO items, or any other notes related to the PR.

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2023-07-31 09:25 UTC, pcnfernando commented
Keeping PR as draft until https://github.com/ballerina-platform/ballerina-spec/issues/1252 is finalized

2023-08-15 04:21 UTC, KavinduZoysa commented on compiler/ballerina-lang/src/main/java/org/wso2/ballerinalang/compiler/semantics/analyzer/QueryTypeChecker.java
> +    private BType getNonContextualQueryType(BType constraintType, BType basicType,  Location pos) {
```suggestion
    private BType getNonContextualQueryType(BType constraintType, BType basicType, Location pos) {
```

2023-08-15 06:15 UTC, NipunaRanasinghe approved these changes
Debugger changes LGTM

2023-08-15 06:53 UTC, malinthar requested changes
Can we add a LS code action test case for the following as well

```Ballerina
public function main() {
    xml x1 = xml `<book>The Lost World</book>`;
    from xml element in x1 select element.toBalString();
}

```

2023-08-15 15:53 UTC, pcnfernando commented
> Can we add a LS code action test case for the following as well
> 
> ```ballerina
> public function main() {
>     xml x1 = xml `<book>The Lost World</book>`;
>     from xml element in x1 select element.toBalString();
> }
> ```

Inferring would result in an error for this specific scenario. Therefore, no code action. Can you point me to a such a codeaction test I can refer

2023-08-15 17:15 UTC, malinthar commented
> > Can we add a LS code action test case for the following as well
> > ```ballerina
> > public function main() {
> >     xml x1 = xml `<book>The Lost World</book>`;
> >     from xml element in x1 select element.toBalString();
> > }
> > ```
> 
> Inferring would result in an error for this specific scenario. Therefore, no code action. Can you point me to a such a codeaction test I can refer

+1. We can add a negative test case in that case

2023-08-15 17:15 UTC, malinthar approved these changes

2023-08-18 08:58 UTC, merged