Suggest ballerina central packages when they're partially typed
ballerina-platform/ballerina-lang pull request #41171
Opened 2023-08-07 18:05 UTC by mindula

## Purpose
This PR adds the implementation to suggest ballerina central packages when partially typed and changes the work done progress notification.

Fixes #40816, #41088

## Samples

<img width="479" alt="Screenshot 2023-08-07 at 23 32 14" src="https://github.com/ballerina-platform/ballerina-lang/assets/61020198/2a407ae7-1220-4135-8b79-ebd40a0b2277">

## Check List 
- [x] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [x] Added necessary tests
  - [x] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2023-08-07 18:25 UTC, KavinduZoysa commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportDeclarationNodeContext.java
> +                packageList.add(packageName);
Let's inline this

2023-08-10 09:13 UTC, malinthar commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportDeclarationNodeContext.java
>              }
Let's add a return here and get rid of the else block

2023-08-10 09:53 UTC, mindula commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/CompletionSearchProvider.java
> +    public void addCentralPackagesToTrie(List<String> packages) {
done

2023-08-10 17:08 UTC, malinthar requested changes

2023-08-11 03:51 UTC, mindula commented on language-server/modules/langserver-core/src/test/resources/completion/import_decl/source/import_decl_with_ballerinax_org3.bal
> +import ballerinax/azure.
+1

2023-08-11 04:53 UTC, KavinduZoysa commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportDeclarationNodeContext.java
> +                packageList.add(packageName);
It seems this is not fixed.

2023-08-11 04:54 UTC, malinthar approved these changes
LGTM!

2023-08-11 05:17 UTC, mindula commented on language-server/modules/langserver-core/src/main/java/org/ballerinalang/langserver/completions/providers/context/ImportDeclarationNodeContext.java
> +                packageList.add(packageName);
Done.

2023-08-11 05:22 UTC, malinthar approved these changes

2023-08-11 06:20 UTC, KavinduZoysa approved these changes

2023-08-11 14:48 UTC, merged