Support passing a custom truststore with central calls
ballerina-platform/ballerina-lang pull request #43621
Opened 2024-11-20 09:39 UTC by azinneera

## Purpose
> Support passing a custom truststore with central calls

## Check List 
- [ ] Read the [Contributing Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- [ ] Updated Change Log
- [ ] Checked Tooling Support (#<Issue Number>)
- [ ] Added necessary tests
  - [ ] Unit Tests
  - [ ] Spec Conformance Tests
  - [ ] Integration Tests
  - [ ] Ballerina By Example Tests
- [ ] Increased Test Coverage   
- [ ] Added necessary documentation  
  - [ ] API documentation 
  - [ ] Module documentation in Module.md files
  - [ ] Ballerina By Examples

2024-11-21 04:46 UTC, gayaldassanayake submitted a review, later dismissed

2024-11-21 06:18 UTC, sameerajayasoma requested changes

2024-11-21 06:18 UTC, sameerajayasoma commented on cli/central-client/src/main/java/org/ballerinalang/central/client/CentralAPIClient.java
> +    private static final String ENV_TRUSTSTORE_PATH = "BALLERINA_TRUSTSTORE_PATH";
Truststore is a java specific term. We need to find a generic term.

2024-11-21 06:36 UTC, sameerajayasoma commented on cli/central-client/src/main/java/org/ballerinalang/central/client/CentralAPIClient.java
> +    private static final String ENV_TRUSTSTORE_PATH = "BALLERINA_TRUSTSTORE_PATH";
https://central.ballerina.io/ballerina/http/2.12.3#ClientSecureSocket

Here we allow a truststore or a single cert.

2024-11-25 14:43 UTC, Dilhasha approved these changes

2024-11-25 17:35 UTC, merged